<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1572;CS1573;CS1591</WarningsAsErrors>
    <InnoAssemblyScope>Editor</InnoAssemblyScope>
  </PropertyGroup>
<ItemGroup>
    <ProjectReference Include="..\Inno.Editor.Core\Inno.Editor.Core.csproj" />
    <ProjectReference Include="..\..\..\..\foundation\core\Inno.Core.Identity\Inno.Core.Identity.csproj" />
    <ProjectReference Include="..\..\..\..\foundation\core\Inno.Core.Events\Inno.Core.Events.csproj" />
    <ProjectReference Include="..\..\..\..\foundation\core\Inno.Core.Input\Inno.Core.Input.csproj" />
    <ProjectReference Include="..\..\..\..\foundation\core\Inno.Core.Mathematics\Inno.Core.Mathematics.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\foundation\core\Inno.Core.Diagnostics\Inno.Core.Diagnostics.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\..\..\foundation\core\Inno.Core.Execution\Inno.Core.Execution.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\..\..\foundation\scripting\Inno.Scripting.Api\Inno.Scripting.Api.csproj" PrivateAssets="compile" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\foundation\core\Inno.Core.Logging\Inno.Core.Logging.csproj" />
    <ProjectReference Include="..\..\..\..\foundation\extensibility\Inno.Extensibility.Types\Inno.Extensibility.Types.csproj" />
  </ItemGroup>
</Project>
