<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1572;CS1573;CS1591</WarningsAsErrors>
    <InnoAssemblyScope>Editor</InnoAssemblyScope>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../framework/Inno.Editor.Inspection/Inno.Editor.Inspection.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../features/Inno.Editor.Shaders/Inno.Editor.Shaders.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../../../foundation/core/Inno.Core.Execution/Inno.Core.Execution.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../features/Inno.Editor.Rendering/Inno.Editor.Rendering.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../Inno.Editor.Panel.FileBrowser/Inno.Editor.Panel.FileBrowser.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../../../foundation/core/Inno.Core.Input/Inno.Core.Input.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../../../../native/Inno.Native.ImGui/Inno.Native.ImGui.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../../../foundation/core/Inno.Core.IO/Inno.Core.IO.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../../../foundation/scripting/Inno.Scripting.Api/Inno.Scripting.Api.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../../../foundation/core/Inno.Core.Serialization/Inno.Core.Serialization.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../../../foundation/extensibility/Inno.Extensibility.Types/Inno.Extensibility.Types.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../../../content/assets/Inno.Assets/Inno.Assets.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../../../content/assets/Inno.Assets.Pipeline/Inno.Assets.Pipeline.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../../../services/rendering/Inno.Rendering/Inno.Rendering.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../../../services/rendering/Inno.Rendering.Shaders/Inno.Rendering.Shaders.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../../../services/rendering/Inno.Rendering.Assets/Inno.Rendering.Assets.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../framework/Inno.Editor.Core/Inno.Editor.Core.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../framework/Inno.Editor.Graph/Inno.Editor.Graph.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../framework/Inno.Editor.Interactions/Inno.Editor.Interactions.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../presentation/Inno.Editor.ImGui/Inno.Editor.ImGui.csproj" PrivateAssets="compile" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../foundation/core/Inno.Core.Graphs/Inno.Core.Graphs.csproj" />
  </ItemGroup>
</Project>
