using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Inno.Runtime.Generators;

/// <summary>
/// Emits a local, explicit type and construction catalog for statically deployed managed assemblies.
/// </summary>
[Generator]
public sealed class RuntimeModuleCatalogGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Registers deterministic catalog generation from the current assembly's declared symbols.
    /// </summary>
    /// <param name="context">
    /// The compiler's incremental registration boundary.
    /// </param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (
            output,
            compilation
        ) => Generate(output, compilation));
    }

    private static void Generate(
        SourceProductionContext output,
        Compilation compilation
    ) {
        if (compilation.AssemblyName is null)
            return;
        INamedTypeSymbol[] types = EnumerateTypes(compilation.Assembly.GlobalNamespace)
            .Where(IsAccessible)
            .OrderBy(static type => type.ToDisplayString(), StringComparer.Ordinal)
            .ToArray();
        var code = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        code.Append("namespace ").Append(compilation.AssemblyName).Append(".Generated;\n\n")
            .Append("/// <summary>\n/// Publishes this assembly's explicit static metadata without scanning its runtime types.\n/// </summary>\n")
            .Append("public static class RuntimeModuleCatalog\n{\n")
            .Append("    /// <summary>\n    /// Gets the assembly owning these declarations.\n    /// </summary>\n")
            .Append("    public static global::System.Reflection.Assembly assembly => typeof(RuntimeModuleCatalog).Assembly;\n\n")
            .Append("    /// <summary>\n    /// Contributes declared types and available parameterless factories to one composition.\n    /// </summary>\n")
            .Append("    /// <param name=\"register\">\n    /// The composition-owned callback; this catalog does not retain it.\n    /// </param>\n")
            .Append("    public static void Register(global::Inno.Extensibility.Catalogs.ITypeCatalogRegistrar register)\n    {\n")
            .Append("        global::System.ArgumentNullException.ThrowIfNull(register);\n");
        var constructors = new List<INamedTypeSymbol>();
        foreach (INamedTypeSymbol type in types)
        {
            string typeName = GetTypeName(type);
            string factory = "null";
            if (CanConstruct(type))
            {
                IMethodSymbol? constructor = type.InstanceConstructors.FirstOrDefault(static value => value.Parameters.Length == 0);
                if (constructor is not null && constructor.DeclaredAccessibility is not
                    (Accessibility.Public or Accessibility.Internal or Accessibility.ProtectedOrInternal))
                {
                    factory = FormatConstructorCall(type, constructors.Count);
                    constructors.Add(type);
                }
                else
                {
                    factory = "static () => new " + typeName + "()";
                }
            }
            code.Append("        register.Register(new global::Inno.Extensibility.Catalogs.TypeCatalogMetadata(typeof(")
                .Append(typeName).Append(")")
                .Append(", ").Append(FormatTypes(GetBaseTypes(type)))
                .Append(", ").Append(FormatTypes(type.AllInterfaces))
                .Append(", ").Append(FormatAttributes(type.GetAttributes()))
                .Append(", ").Append(FormatAttributes(GetInheritedAttributes(type)))
                .Append(", ").Append(FormatOverrides(type)).Append("), ").Append(factory).Append(");\n");
        }
        var constructions = RuntimeTypeCatalogGenerator.Analyze(compilation, output);
        foreach (INamedTypeSymbol type in constructions.factories.Where(static type => !CanConstruct(type) &&
            GetBaseTypes(type).Any(static parent => parent.OriginalDefinition.ToDisplayString() ==
                "Inno.Core.Serialization.Converters.SerializationConverter<T>")))
            RuntimeRegistrationDiagnostics.ReportUnavailable(output, type,
                "a nonabstract converter with a parameterless constructor is required");
        foreach (INamedTypeSymbol type in constructions.factories.Where(CanConstruct))
        {
            string name = GetTypeName(type);
            IMethodSymbol? constructor = type.InstanceConstructors.FirstOrDefault(static value => value.Parameters.Length == 0);
            string factory;
            if (constructor is not null && constructor.DeclaredAccessibility is not
                (Accessibility.Public or Accessibility.Internal or Accessibility.ProtectedOrInternal))
            {
                factory = FormatConstructorCall(type, constructors.Count);
                constructors.Add(type);
            }
            else
            {
                factory = "static () => new " + name + "()";
            }
            code.Append("        register.RegisterFactory(typeof(").Append(name).Append("), ").Append(factory).Append(");\n");
        }
        foreach (var rejection in constructions.rejected)
        {
            code.Append("        register.RejectGenericConstruction(typeof(").Append(GetTypeName(rejection.definition))
                .Append("), new global::System.Type[] { ")
                .Append(string.Join(", ", rejection.arguments.Select(argument => "typeof(" + FormatType(argument) + ")")))
                .Append(" });\n");
        }
        if (types.Any(static type => type.GetAttributes().Any(static attribute =>
            attribute.AttributeClass?.ToDisplayString() == "Inno.Core.Serialization.GenerateSerializationConverterAttribute")))
        {
            code.Append("        global::").Append(compilation.AssemblyName)
                .Append(".Generated.RuntimeSerializationCatalog.Register(register);\n");
        }
        code.Append("    }\n");
        code.Append("\n    /// <summary>\n    /// Resolves an explicitly registered declaration by its CLR metadata name.\n    /// </summary>\n")
            .Append("    /// <param name=\"metadataName\">\n    /// The exact name emitted by the owning catalog.\n    /// </param>\n")
            .Append("    /// <returns>\n    /// The linked declaration; unknown names throw instead of probing assemblies.\n    /// </returns>\n")
            .Append("    /// <exception cref=\"global::System.ArgumentException\">\n    /// The declaration is absent from this catalog.\n    /// </exception>\n")
            .Append("    public static global::System.Type ResolveType(string metadataName) => metadataName switch\n    {\n");
        foreach (INamedTypeSymbol type in types)
        {
            code.Append("        ").Append(Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(GetMetadataName(type), quote: true))
                .Append(" => typeof(").Append(GetTypeName(type)).Append("),\n");
        }
        code.Append("        _ => throw new global::System.ArgumentException(\"The declaration is not registered in this assembly.\", nameof(metadataName))\n    };\n");
        for (int index = 0; index < constructors.Count; index++)
        {
            AppendConstructor(code, constructors[index], index);
        }
        code.Append("}\n");
        output.AddSource("Registration/RuntimeModules.g.cs", code.ToString());
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateTypes(INamespaceSymbol source)
    {
        foreach (INamespaceSymbol child in source.GetNamespaceMembers())
        {
            foreach (INamedTypeSymbol type in EnumerateTypes(child))
                yield return type;
        }
        foreach (INamedTypeSymbol type in source.GetTypeMembers())
        {
            yield return type;
            foreach (INamedTypeSymbol nested in EnumerateNestedTypes(type))
                yield return nested;
        }
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateNestedTypes(INamedTypeSymbol source)
    {
        foreach (INamedTypeSymbol type in source.GetTypeMembers())
        {
            yield return type;
            foreach (INamedTypeSymbol nested in EnumerateNestedTypes(type))
                yield return nested;
        }
    }

    private static bool IsAccessible(INamedTypeSymbol type)
    {
        for (INamedTypeSymbol? current = type; current is not null; current = current.ContainingType)
        {
            if (current.DeclaredAccessibility is not
                (Accessibility.Public or Accessibility.Internal or Accessibility.ProtectedOrInternal) || current.IsFileLocal)
                return false;
        }
        return !type.IsImplicitlyDeclared && type.TypeKind != TypeKind.Error;
    }

    private static bool CanConstruct(INamedTypeSymbol type)
    {
        for (INamedTypeSymbol? current = type; current is not null; current = current.ContainingType)
        {
            if (HasOpenArguments(current))
                return false;
        }
        return !type.IsAbstract && !type.IsStatic && type.TypeKind is TypeKind.Class or TypeKind.Struct &&
            !type.IsRefLikeType && !GetBaseTypes(type).Append(type).Any(static current =>
                current.GetMembers().Any(static member => member is IPropertySymbol { IsRequired: true }
                    or IFieldSymbol { IsRequired: true })) &&
            type.InstanceConstructors.Any(static constructor => constructor.Parameters.Length == 0);
    }

    private static string FormatConstructorCall(
        INamedTypeSymbol type,
        int index
    ) {
        ITypeSymbol[] arguments = GetConstructionArguments(type).ToArray();
        return "static () => Constructor" + index + (arguments.Length == 0 ? string.Empty :
            "<" + string.Join(", ", arguments.Select(FormatType)) + ">") + ".Create()";
    }

    private static IEnumerable<ITypeSymbol> GetConstructionArguments(INamedTypeSymbol type)
    {
        if (type.ContainingType is not null)
        {
            foreach (ITypeSymbol argument in GetConstructionArguments(type.ContainingType))
                yield return argument;
        }
        foreach (ITypeSymbol argument in type.TypeArguments)
            yield return argument;
    }

    private static void AppendConstructor(
        StringBuilder code,
        INamedTypeSymbol type,
        int index
    ) {
        INamedTypeSymbol definition = type.OriginalDefinition;
        ITypeParameterSymbol[] parameters = GetConstructionArguments(definition).Cast<ITypeParameterSymbol>().ToArray();
        var names = new Dictionary<ISymbol, string>(SymbolEqualityComparer.Default);
        for (int parameterIndex = 0; parameterIndex < parameters.Length; parameterIndex++)
            names.Add(parameters[parameterIndex], "T" + parameterIndex);
        code.Append("\n    private static class Constructor").Append(index);
        if (parameters.Length > 0)
            code.Append('<').Append(string.Join(", ", parameters.Select(parameter => names[parameter]))).Append('>');
        foreach (ITypeParameterSymbol parameter in parameters)
        {
            var constraints = new List<string>();
            if (parameter.HasUnmanagedTypeConstraint)
                constraints.Add("unmanaged");
            else if (parameter.HasValueTypeConstraint)
                constraints.Add("struct");
            else if (parameter.HasReferenceTypeConstraint)
                constraints.Add(parameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class");
            else if (parameter.HasNotNullConstraint)
                constraints.Add("notnull");
            constraints.AddRange(parameter.ConstraintTypes.Select(constraint => FormatConstructionType(constraint, names)));
            if (parameter.HasConstructorConstraint)
                constraints.Add("new()");
            if (constraints.Count > 0)
                code.Append("\n        where ").Append(names[parameter]).Append(" : ").Append(string.Join(", ", constraints));
        }
        code.Append("\n    {\n")
            .Append("        [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Constructor)]\n")
            .Append("        internal static extern ").Append(FormatConstructionType(definition, names))
            .Append(" Create();\n    }\n");
    }

    private static string FormatConstructionType(
        ITypeSymbol type,
        Dictionary<ISymbol, string> names
    ) => string.Concat(type.ToDisplayParts(SymbolDisplayFormat.FullyQualifiedFormat).Select(part =>
        part.Symbol is not null && names.TryGetValue(part.Symbol, out string? name) ? name : part.ToString()));

    private static IEnumerable<INamedTypeSymbol> GetBaseTypes(INamedTypeSymbol type)
    {
        for (INamedTypeSymbol? current = type.BaseType; current is not null && current.SpecialType != SpecialType.System_Object;
            current = current.BaseType)
            yield return current;
    }

    private static string FormatTypes(IEnumerable<INamedTypeSymbol> types)
        => "new global::System.Type[] { " + string.Join(", ", types.Where(IsAccessible)
            .Select(FormatTypeReference)) + " }";

    private static string FormatTypeReference(INamedTypeSymbol type)
    {
        bool isInternal = type.DeclaredAccessibility is Accessibility.Internal or Accessibility.ProtectedAndInternal;
        if (isInternal && !type.Locations.Any(static location => location.IsInSource) &&
            type.ContainingAssembly.Name.StartsWith("Inno.", StringComparison.Ordinal))
        {
            return "global::" + type.ContainingAssembly.Name + ".Generated.RuntimeModuleCatalog.ResolveType(" +
                Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(GetMetadataName(type), quote: true) + ")";
        }
        return "typeof(" + GetTypeName(type) + ")";
    }

    private static string GetMetadataName(INamedTypeSymbol type)
        => type.ContainingType is not null ? GetMetadataName(type.ContainingType) + "+" + type.MetadataName
            : (type.ContainingNamespace.IsGlobalNamespace ? string.Empty : type.ContainingNamespace.ToDisplayString() + ".") +
                type.MetadataName;

    private static string FormatOverrides(INamedTypeSymbol type)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var declarations = new List<string>();
        foreach (INamedTypeSymbol owner in new[] { type }.Concat(GetBaseTypes(type)))
        {
            foreach (IMethodSymbol method in owner.GetMembers().OfType<IMethodSymbol>().Where(static method =>
                !method.IsStatic && !method.IsGenericMethod && method.Parameters.Length == 0 &&
                method.MethodKind == MethodKind.Ordinary))
            {
                if (!seen.Add(method.Name) || !method.IsOverride)
                    continue;
                IMethodSymbol root = method;
                while (root.OverriddenMethod is not null)
                    root = root.OverriddenMethod;
                declarations.Add("(" + Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(method.Name, quote: true) +
                    ", typeof(" + GetTypeName(root.ContainingType) + "))");
            }
        }
        return "new (string, global::System.Type)[] { " + string.Join(", ", declarations) + " }";
    }

    private static IEnumerable<AttributeData> GetInheritedAttributes(INamedTypeSymbol type)
    {
        var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        bool inherited = false;
        foreach (INamedTypeSymbol declaration in new[] { type }.Concat(GetBaseTypes(type)))
        {
            foreach (AttributeData attribute in declaration.GetAttributes())
            {
                if (attribute.AttributeClass is not INamedTypeSymbol attributeType)
                    continue;
                AttributeData? usage = new[] { attributeType }.Concat(GetBaseTypes(attributeType))
                    .SelectMany(static source => source.GetAttributes())
                    .FirstOrDefault(static value => value.AttributeClass?.ToDisplayString() == "System.AttributeUsageAttribute");
                bool allowMultiple = usage?.NamedArguments.Any(static pair => pair.Key == "AllowMultiple" &&
                    pair.Value.Value is true) ?? false;
                bool canInherit = !(usage?.NamedArguments.Any(static pair => pair.Key == "Inherited" &&
                    pair.Value.Value is false) ?? false);
                if (inherited && (!canInherit || !allowMultiple && seen.Contains(attributeType)))
                    continue;
                seen.Add(attributeType);
                yield return attribute;
            }
            inherited = true;
        }
    }

    private static string FormatAttributes(IEnumerable<AttributeData> attributes)
        => "new global::System.Attribute[] { " + string.Join(", ", attributes
            .Where(static attribute => attribute.AttributeClass is not null && IsAccessible(attribute.AttributeClass) &&
                attribute.AttributeConstructor?.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal)
            .Select(static attribute => "new " + GetTypeName(attribute.AttributeClass!) + "(" +
                string.Join(", ", attribute.ConstructorArguments.Select(FormatConstant)) + ")" +
                (attribute.NamedArguments.Length == 0 ? string.Empty : " { " + string.Join(", ", attribute.NamedArguments
                    .Select(static pair => pair.Key + " = " + FormatConstant(pair.Value))) + " }"))) + " }";

    private static string FormatConstant(TypedConstant constant)
    {
        if (constant.IsNull)
            return "null";
        if (constant.Kind == TypedConstantKind.Type && constant.Value is ITypeSymbol type)
            return "typeof(" + FormatType(type) + ")";
        if (constant.Kind == TypedConstantKind.Array && constant.Type is IArrayTypeSymbol array)
            return "new " + array.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + "[] { " +
                string.Join(", ", constant.Values.Select(FormatConstant)) + " }";
        string literal = Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatPrimitive(constant.Value!, quoteStrings: true,
            useHexadecimalNumbers: false);
        return constant.Kind == TypedConstantKind.Enum ? "(" +
            constant.Type!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + ")" + literal : literal;
    }

    private static string GetTypeName(INamedTypeSymbol type)
    {
        if (!HasOpenArguments(type))
            return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string arguments = type.Arity == 0 ? string.Empty : "<" + new string(',', type.Arity - 1) + ">";
        if (type.ContainingType is not null)
            return GetTypeName(type.ContainingType) + "." + type.Name + arguments;
        if (type.Arity > 0)
            return "global::" + (type.ContainingNamespace.IsGlobalNamespace ? string.Empty :
                type.ContainingNamespace.ToDisplayString() + ".") + type.Name + arguments;
        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    private static bool HasOpenArguments(INamedTypeSymbol type)
        => type.IsUnboundGenericType || type.TypeArguments.Any(static argument => argument is ITypeParameterSymbol ||
            argument is INamedTypeSymbol named && HasOpenArguments(named)) ||
            type.ContainingType is not null && HasOpenArguments(type.ContainingType);

    private static string FormatType(ITypeSymbol type)
        => type switch
        {
            INamedTypeSymbol named => GetTypeName(named),
            IArrayTypeSymbol array => FormatType(array.ElementType) + "[" + new string(',', array.Rank - 1) + "]",
            _ => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
        };
}
