using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Inno.Runtime.Generators;

/// <summary>
/// Composes explicit assembly-local metadata catalogs for a Player entry project selected by its build.
/// </summary>
[Generator]
public sealed class RuntimeFactoryGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var inputs = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);
        context.RegisterSourceOutput(inputs, static (
            output,
            input
        ) => {
            if (!input.Right.GlobalOptions.TryGetValue("build_property.InnoGeneratePlayerComposition", out string? enabled)
                || !string.Equals(enabled, "true", StringComparison.OrdinalIgnoreCase))
                return;
            Generate(output, input.Left);
        });
    }

    private static void Generate(
        SourceProductionContext output,
        Compilation compilation
    ) {
        string assemblyName = compilation.AssemblyName!;
        string? deploymentDefinition = compilation.GetTypeByMetadataName(
            assemblyName + ".Generated.PlayerDeploymentDefinition")?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var catalogs = new List<(string name, bool host)>();
        foreach (IAssemblySymbol assembly in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            if (assembly.GetTypeByMetadataName(assembly.Name + ".Generated.RuntimeModuleCatalog") is null)
                continue;
            string? domain = assembly.GetAttributes()
                .Where(static attribute => attribute.AttributeClass?.ToDisplayString()
                    == "System.Reflection.AssemblyMetadataAttribute" && attribute.ConstructorArguments.Length == 2)
                .Where(static attribute => attribute.ConstructorArguments[0].Value as string == "Inno.AssemblyDomain")
                .Select(static attribute => attribute.ConstructorArguments[1].Value as string)
                .FirstOrDefault();
            catalogs.Add((assembly.Name, domain is "InnoInternal"));
        }
        catalogs.Add((assemblyName, true));
        catalogs.Sort(static (
            left,
            right
        ) => StringComparer.Ordinal.Compare(left.name, right.name));
        var code = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        code.Append("namespace ").Append(assemblyName).Append(".Generated;\n\n")
            .Append("internal static class PlayerMetadataComposition\n{\n")
            .Append("    internal static global::Inno.Extensibility.Modules.IAssemblyCatalogSource CreateModules() =>\n")
            .Append("        new global::Inno.Runtime.StaticAssemblyCatalogSource([\n");
        foreach (var catalog in catalogs.Where(static catalog => catalog.host))
            code.Append("            global::").Append(catalog.name).Append(".Generated.RuntimeModuleCatalog.assembly,\n");
        code.Append("        ], [typeof(object).Assembly]);\n\n")
            .Append("    internal static global::Inno.Extensibility.Types.ITypeCatalogSource CreateTypes() =>\n")
            .Append("        new global::Inno.Runtime.StaticTypeCatalogSource([\n");
        foreach (var catalog in catalogs)
            code.Append("            global::").Append(catalog.name).Append(".Generated.RuntimeModuleCatalog.Register,\n");
        code.Append("        ]);\n\n")
            .Append("    internal static global::Inno.Core.Serialization.ISerializationMetadataSource CreateSerialization() =>\n")
            .Append("        new global::Inno.Core.Serialization.StaticSerializationMetadataSource([\n");
        foreach (IAssemblySymbol assembly in compilation.SourceModule.ReferencedAssemblySymbols
            .OrderBy(static assembly => assembly.Name, StringComparer.Ordinal))
            if (assembly.GetTypeByMetadataName(assembly.Name + ".Generated.RuntimeSerializationMetadataCatalog") is not null)
                code.Append("            global::").Append(assembly.Name).Append(".Generated.RuntimeSerializationMetadataCatalog.Register,\n");
        code.Append("            global::").Append(assemblyName).Append(".Generated.RuntimeSerializationMetadataCatalog.Register,\n")
            .Append("        ]);\n\n")
            .Append("    internal static global::Inno.Player.Runtime.IPlayerModuleActivator CreateActivator() =>\n")
            .Append("        new global::Inno.Player.Runtime.StaticPlayerModuleActivator(\n");
        if (deploymentDefinition is null)
        {
            code.Append("            new global::Inno.Runtime.GameCodeDeployment([]),\n")
                .Append("            new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.IReadOnlyList<global::System.Reflection.Assembly>>());\n");
        }
        else
        {
            code.Append("            ").Append(deploymentDefinition).Append(".CreateDeployment(),\n")
                .Append("            ").Append(deploymentDefinition).Append(".CreateAssemblies());\n");
        }
        code.Append("}\n");
        output.AddSource("Registration/RuntimeFactories.g.cs", code.ToString());
    }
}
