<Project>
  <Import Project="$(InnoNativeBindingSelection)" Condition="'$(InnoNativeBindingSelection)' != '' and Exists('$(InnoNativeBindingSelection)')" />
  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)/obj/**;$(MSBuildProjectDirectory)/bin/**</DefaultItemExcludes>
  </PropertyGroup>
  <PropertyGroup Condition="'$(InnoNativeTarget)' == '' and ('$(MSBuildProjectName)' == 'Inno.Player.Browser' or '$(RuntimeIdentifier)' == 'browser-wasm')">
    <InnoNativeTarget>browser-wasm</InnoNativeTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(InnoNativeTarget)' != ''">
    <BaseIntermediateOutputPath>obj/$(InnoNativeTarget)/</BaseIntermediateOutputPath>
    <BaseOutputPath>bin/$(InnoNativeTarget)/</BaseOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(InnoNativeTarget)' != '' and '$(InnoNativeBuildFingerprint)' != ''">
    <BaseIntermediateOutputPath>obj/$(InnoNativeTarget)/$(InnoNativeBuildFingerprint)/</BaseIntermediateOutputPath>
    <BaseOutputPath>bin/$(InnoNativeTarget)/$(InnoNativeBuildFingerprint)/</BaseOutputPath>
  </PropertyGroup>
</Project>
