<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1572;CS1573;CS1591</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Inno.UI\Inno.UI.csproj" />
    <ProjectReference Include="..\..\input\Inno.Input\Inno.Input.csproj" />
    <ProjectReference Include="..\..\text\Inno.Text\Inno.Text.csproj" />
    <ProjectReference Include="..\..\..\content\assets\Inno.Assets\Inno.Assets.csproj" />
    <ProjectReference Include="..\..\..\runtime\contracts\Inno.Runtime.Contracts\Inno.Runtime.Contracts.csproj" />
  </ItemGroup>
</Project>
