using Inno.Rendering.Runtime;
using Inno.Scripting.Api;

[assembly: ScriptingApiNamespace("InnoEngine.Rendering", "Inno.Rendering.Runtime", ScriptingApiScope.Runtime)]

[assembly: ScriptingApiExport(typeof(RenderTargetArtifactStatus), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderFrameData), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderRequest), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IRenderRequestSink), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderRequestProviderExtensionAttribute), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderRequestProviderContext), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderRequestProvider), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderView), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderOutputInput), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderOutputSession), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderOutputRoute), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderOutputLayer), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderModelOutput), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IRenderModel), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderModelExtensionAttribute), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ViewContentContext), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ViewContentItem), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IViewDrawable), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IViewPointerTarget), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IPreparedViewDrawable), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IViewContentSink), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IViewContentSource), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IViewContentFrameSource), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ViewContentSourceExtensionAttribute), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IViewContentCollector), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(SelectedViewContentCollector), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPersistentResourceId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTextureSubresourceData), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderGeometrySection), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderGeometry), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderMaterialPass), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IRenderResourceService), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderExtensionStateContext), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipelineExtensionAttribute), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderFeatureExtensionAttribute), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderResourceMap), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipelineContext), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderFeatureContext), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipeline), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipelineFeature), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(GraphicsSettings), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderFrameStatistics), ScriptingApiScope.Runtime)]
