using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text;

using Inno.Scripting.Api;

namespace Inno.Scripting.Compiler;

internal static class ScriptApiStubSourceBuilder
{
    private const BindingFlags C_DECLARED_MEMBERS =
        BindingFlags.Public |
        BindingFlags.NonPublic |
        BindingFlags.Instance |
        BindingFlags.Static |
        BindingFlags.DeclaredOnly;

    [ThreadStatic]
    private static IReadOnlySet<Type>? s_exportedTypes;

    [ThreadStatic]
    private static IReadOnlyDictionary<string, string>? s_namespaceMappings;

    [ThreadStatic]
    private static IReadOnlyDictionary<Type, string>? s_typeNames;

    [ThreadStatic]
    private static NullabilityInfoContext? s_nullability;

    internal static string BuildImplementation(
        ScriptApiAssembly export,
        IReadOnlySet<Type> exportedTypes)
        => Build(
            export.exports.Select(static value => value.type).ToArray(),
            exportedTypes,
            export.assembly.GetName().Version ?? new Version(1, 0, 0, 0),
            namespaceMappings: null,
            typeNames: null);

    internal static string BuildLogical(
        IReadOnlyList<ScriptApiTypeExport> exports,
        IReadOnlySet<Type> exportedTypes,
        IReadOnlyDictionary<string, string> namespaceMappings)
        => Build(
            exports.Select(static value => value.type).ToArray(),
            exportedTypes,
            new Version(1, 0, 0, 0),
            namespaceMappings,
            exports.ToDictionary(static value => value.type, static value => value.name));

    private static string Build(
        IReadOnlyList<Type> types,
        IReadOnlySet<Type> exportedTypes,
        Version version,
        IReadOnlyDictionary<string, string>? namespaceMappings,
        IReadOnlyDictionary<Type, string>? typeNames)
    {
        s_exportedTypes = exportedTypes;
        s_namespaceMappings = namespaceMappings;
        s_typeNames = typeNames;
        s_nullability = new NullabilityInfoContext();
        try
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.Append("[assembly: global::System.Reflection.AssemblyVersion(\"")
                .Append(version)
                .AppendLine("\")]");
            foreach (Type type in types.OrderBy(static value => value.FullName, StringComparer.Ordinal))
            {
                builder.Append("namespace ")
                    .Append(ResolveNamespace(type.Namespace ?? string.Empty))
                    .AppendLine()
                    .AppendLine("{");
                AppendType(builder, type);
                builder.AppendLine("}").AppendLine();
            }
            return builder.ToString();
        }
        finally
        {
            s_exportedTypes = null;
            s_namespaceMappings = null;
            s_typeNames = null;
            s_nullability = null;
        }
    }

    private static void AppendType(StringBuilder builder, Type type)
    {
        if (type.IsEnum)
        {
            AppendEnum(builder, type);
            return;
        }
        if (typeof(MulticastDelegate).IsAssignableFrom(type.BaseType))
        {
            AppendDelegate(builder, type);
            return;
        }

        AppendAttributeUsage(builder, type);
        builder.Append("public ");
        if (type.IsClass)
        {
            if (type.IsAbstract && type.IsSealed)
                builder.Append("static ");
            else
            {
                if (type.IsAbstract)
                    builder.Append("abstract ");
                if (type.IsSealed)
                    builder.Append("sealed ");
            }
            builder.Append("class ");
        }
        else if (type.IsInterface)
        {
            builder.Append("interface ");
        }
        else
        {
            if (type.IsDefined(typeof(System.Runtime.CompilerServices.IsReadOnlyAttribute), inherit: false))
                builder.Append("readonly ");
            builder.Append("struct ");
        }
        AppendNamedType(builder, type);
        AppendBaseTypes(builder, type);
        AppendGenericConstraints(builder, type.GetGenericArguments().Where(static value => value.DeclaringMethod is null));
        builder.AppendLine().AppendLine("{");
        AppendFields(builder, type);
        AppendConstructors(builder, type);
        AppendProperties(builder, type);
        AppendEvents(builder, type);
        AppendMethods(builder, type);
        builder.AppendLine("}");
    }

    private static void AppendAttributeUsage(StringBuilder builder, Type type)
    {
        if (!typeof(Attribute).IsAssignableFrom(type))
            return;
        AttributeUsageAttribute usage = type.GetCustomAttribute<AttributeUsageAttribute>(inherit: true)
            ?? new AttributeUsageAttribute(AttributeTargets.All);
        builder.Append("[global::System.AttributeUsage((global::System.AttributeTargets)")
            .Append(((int)usage.ValidOn).ToString(CultureInfo.InvariantCulture))
            .Append(", AllowMultiple = ")
            .Append(usage.AllowMultiple ? "true" : "false")
            .Append(", Inherited = ")
            .Append(usage.Inherited ? "true" : "false")
            .AppendLine(")]");
    }

    private static void AppendEnum(StringBuilder builder, Type type)
    {
        builder.Append("public enum ")
            .Append(GetTypeName(type))
            .Append(" : ")
            .Append(FormatType(Enum.GetUnderlyingType(type)))
            .AppendLine()
            .AppendLine("{");
        foreach (FieldInfo field in type.GetFields(BindingFlags.Public | BindingFlags.Static))
        {
            object value = field.GetRawConstantValue()!;
            builder.Append("    ")
                .Append(EscapeIdentifier(field.Name))
                .Append(" = ")
                .Append(FormatNumericConstant(value))
                .AppendLine(",");
        }
        builder.AppendLine("}");
    }

    private static void AppendDelegate(StringBuilder builder, Type type)
    {
        MethodInfo invoke = type.GetMethod("Invoke")
            ?? throw new InvalidOperationException($"Delegate '{type.FullName}' has no Invoke method.");
        builder.Append("public delegate ")
            .Append(FormatParameterType(invoke.ReturnParameter))
            .Append(' ');
        AppendNamedType(builder, type);
        builder.Append('(');
        AppendParameters(builder, invoke.GetParameters());
        builder.Append(')');
        AppendGenericConstraints(builder, type.GetGenericArguments());
        builder.AppendLine(";");
    }

    private static void AppendNamedType(StringBuilder builder, Type type)
    {
        builder.Append(GetTypeName(type));
        Type[] arguments = type.GetGenericArguments()
            .Where(static argument => argument.DeclaringMethod is null)
            .ToArray();
        if (arguments.Length == 0)
            return;
        builder.Append('<');
        for (int i = 0; i < arguments.Length; i++)
        {
            if (i > 0)
                builder.Append(", ");
            GenericParameterAttributes variance = arguments[i].GenericParameterAttributes &
                                                  GenericParameterAttributes.VarianceMask;
            if (variance == GenericParameterAttributes.Covariant)
                builder.Append("out ");
            else if (variance == GenericParameterAttributes.Contravariant)
                builder.Append("in ");
            builder.Append(arguments[i].Name);
        }
        builder.Append('>');
    }

    private static void AppendBaseTypes(StringBuilder builder, Type type)
    {
        var baseTypes = new List<Type>();
        if (type.IsClass &&
            !type.IsStaticClass() &&
            type.BaseType is not null &&
            type.BaseType != typeof(object) &&
            IsApiType(type.BaseType))
        {
            baseTypes.Add(type.BaseType);
        }
        foreach (Type interfaceType in type.GetInterfaces())
        {
            if ((interfaceType.IsPublic || interfaceType.IsNestedPublic) &&
                IsApiType(interfaceType) &&
                CanExposeInterface(type, interfaceType))
            {
                baseTypes.Add(interfaceType);
            }
        }
        if (baseTypes.Count == 0)
            return;
        builder.Append(" : ")
            .Append(string.Join(", ", baseTypes.Distinct().Select(FormatType)));
    }

    private static bool CanExposeInterface(Type type, Type interfaceType)
    {
        if (type.IsInterface)
            return true;
        InterfaceMapping mapping = type.GetInterfaceMap(interfaceType);
        return mapping.TargetMethods.All(IsVisible);
    }

    private static void AppendGenericConstraints(
        StringBuilder builder,
        IEnumerable<Type> genericParameters)
    {
        foreach (Type parameter in genericParameters)
        {
            GenericParameterAttributes attributes = parameter.GenericParameterAttributes;
            var constraints = new List<string>();
            if ((attributes & GenericParameterAttributes.ReferenceTypeConstraint) != 0)
                constraints.Add("class");
            bool isStruct = (attributes & GenericParameterAttributes.NotNullableValueTypeConstraint) != 0;
            if (isStruct)
                constraints.Add("struct");
            constraints.AddRange(parameter
                .GetGenericParameterConstraints()
                .Where(constraint => constraint != typeof(ValueType))
                .Select(FormatType));
            if (!isStruct && (attributes & GenericParameterAttributes.DefaultConstructorConstraint) != 0)
                constraints.Add("new()");
            if (constraints.Count > 0)
            {
                builder.Append(" where ")
                    .Append(parameter.Name)
                    .Append(" : ")
                    .Append(string.Join(", ", constraints));
            }
        }
    }

    private static void AppendFields(StringBuilder builder, Type type)
    {
        foreach (FieldInfo field in type.GetFields(C_DECLARED_MEMBERS))
        {
            if (!IsVisible(field) || field.IsSpecialName)
                continue;
            if (!IsApiType(field.FieldType))
            {
                RejectUnclosedMember(field, field.FieldType);
                continue;
            }
            builder.Append("    ")
                .Append(GetAccessibility(field))
                .Append(' ');
            if (field.IsLiteral)
                builder.Append("const ");
            else
            {
                if (field.IsStatic)
                    builder.Append("static ");
                if (field.IsInitOnly)
                    builder.Append("readonly ");
            }
            builder.Append(FormatType(field.FieldType, s_nullability!.Create(field), new(field.GetCustomAttributesData(), field)))
                .Append(' ')
                .Append(EscapeIdentifier(field.Name));
            if (field.IsLiteral)
                builder.Append(" = ").Append(FormatConstant(field.GetRawConstantValue(), field.FieldType));
            builder.AppendLine(";");
        }
    }

    private static void AppendConstructors(StringBuilder builder, Type type)
    {
        if (type.IsStaticClass() || type.IsInterface)
            return;
        foreach (ConstructorInfo constructor in type.GetConstructors(C_DECLARED_MEMBERS))
        {
            if (!IsVisible(constructor) || type.IsValueType && constructor.GetParameters().Length == 0)
                continue;
            if (!AreApiParameters(constructor.GetParameters()))
            {
                RejectUnclosedMember(constructor, constructor.GetParameters().Select(static value => value.ParameterType));
                continue;
            }
            builder.Append("    ")
                .Append(GetAccessibility(constructor))
                .Append(' ')
                .Append(GetTypeName(type))
                .Append('(');
            AppendParameters(builder, constructor.GetParameters());
            builder.AppendLine(") => throw new global::System.NotImplementedException();");
        }
    }

    private static void AppendProperties(StringBuilder builder, Type type)
    {
        foreach (PropertyInfo property in type.GetProperties(C_DECLARED_MEMBERS))
        {
            MethodInfo? getter = IsVisible(property.GetMethod) ? property.GetMethod : null;
            MethodInfo? setter = IsVisible(property.SetMethod) ? property.SetMethod : null;
            MethodInfo? representative = MoreVisible(getter, setter);
            if (representative is null)
                continue;
            if (!IsApiType(property.PropertyType) || !AreApiParameters(property.GetIndexParameters()))
            {
                RejectUnclosedMember(
                    property,
                    new[] { property.PropertyType }.Concat(
                        property.GetIndexParameters().Select(static value => value.ParameterType)));
                continue;
            }
            string accessibility = GetAccessibility(representative);
            builder.Append("    ")
                .Append(accessibility)
                .Append(' ');
            AppendMethodModifiers(builder, representative, type.IsInterface);
            builder.Append(FormatType(property.PropertyType, s_nullability!.Create(property), new(property.GetCustomAttributesData(), property))).Append(' ');
            ParameterInfo[] indexParameters = property.GetIndexParameters();
            if (indexParameters.Length > 0)
            {
                builder.Append("this[");
                AppendParameters(builder, indexParameters);
                builder.Append(']');
            }
            else
            {
                builder.Append(EscapeIdentifier(property.Name));
            }
            builder.AppendLine().AppendLine("    {");
            AppendAccessor(builder, "get", getter, accessibility);
            AppendAccessor(builder, "set", setter, accessibility);
            builder.AppendLine("    }");
        }
    }

    private static void AppendAccessor(
        StringBuilder builder,
        string keyword,
        MethodInfo? method,
        string propertyAccessibility)
    {
        if (method is null)
            return;
        builder.Append("        ");
        string accessibility = GetAccessibility(method);
        if (!string.Equals(accessibility, propertyAccessibility, StringComparison.Ordinal))
            builder.Append(accessibility).Append(' ');
        builder.Append(keyword);
        if (method.IsAbstract)
            builder.AppendLine(";");
        else
            builder.AppendLine(" => throw new global::System.NotImplementedException();");
    }

    private static void AppendEvents(StringBuilder builder, Type type)
    {
        foreach (EventInfo eventInfo in type.GetEvents(C_DECLARED_MEMBERS))
        {
            MethodInfo? accessor = MoreVisible(eventInfo.AddMethod, eventInfo.RemoveMethod);
            if (!IsVisible(accessor))
                continue;
            if (!IsApiType(eventInfo.EventHandlerType!))
            {
                RejectUnclosedMember(eventInfo, eventInfo.EventHandlerType!);
                continue;
            }
            builder.Append("    ")
                .Append(GetAccessibility(accessor!))
                .Append(' ');
            if (accessor!.IsStatic)
                builder.Append("static ");
            builder.Append("event ")
                .Append(FormatType(eventInfo.EventHandlerType!, s_nullability!.Create(eventInfo), new(eventInfo.GetCustomAttributesData(), eventInfo)))
                .Append(' ')
                .Append(EscapeIdentifier(eventInfo.Name))
                .AppendLine(";");
        }
    }

    private static void AppendMethods(StringBuilder builder, Type type)
    {
        foreach (MethodInfo method in type.GetMethods(C_DECLARED_MEMBERS))
        {
            if (!IsVisible(method) ||
                method.Name == "Finalize" && method.GetParameters().Length == 0 ||
                method.Name.Contains('<', StringComparison.Ordinal))
                continue;
            if (method.IsSpecialName &&
                method.Name is not "op_Implicit" and not "op_Explicit" &&
                !TryGetOperator(method.Name, out _))
            {
                continue;
            }
            if (!IsApiMethod(method))
            {
                RejectUnclosedMember(
                    method,
                    new[] { method.ReturnType }
                        .Concat(method.GetParameters().Select(static value => value.ParameterType))
                        .Concat(method.GetGenericArguments()
                            .SelectMany(static argument => argument.GetGenericParameterConstraints())));
                continue;
            }
            if (method.IsSpecialName)
            {
                if (method.Name is "op_Implicit" or "op_Explicit")
                    AppendConversionOperator(builder, method);
                else if (TryGetOperator(method.Name, out string? symbol))
                    AppendOperator(builder, method, symbol!);
                continue;
            }
            builder.Append("    ")
                .Append(GetAccessibility(method))
                .Append(' ');
            AppendMethodModifiers(builder, method, type.IsInterface);
            builder.Append(FormatParameterType(method.ReturnParameter))
                .Append(' ')
                .Append(EscapeIdentifier(method.Name));
            Type[] genericArguments = method.GetGenericArguments();
            if (genericArguments.Length > 0)
                builder.Append('<').Append(string.Join(", ", genericArguments.Select(static value => value.Name))).Append('>');
            builder.Append('(');
            AppendParameters(builder, method.GetParameters());
            builder.Append(')');
            AppendGenericConstraints(builder, genericArguments);
            AppendMethodBody(builder, method);
        }
    }

    private static void AppendConversionOperator(StringBuilder builder, MethodInfo method)
    {
        builder.Append("    public static ")
            .Append(method.Name == "op_Implicit" ? "implicit" : "explicit")
            .Append(" operator ")
            .Append(FormatParameterType(method.ReturnParameter))
            .Append('(');
        AppendParameters(builder, method.GetParameters());
        builder.AppendLine(") => throw new global::System.NotImplementedException();");
    }

    private static void AppendOperator(StringBuilder builder, MethodInfo method, string symbol)
    {
        builder.Append("    public static ")
            .Append(FormatParameterType(method.ReturnParameter))
            .Append(" operator ")
            .Append(symbol)
            .Append('(');
        AppendParameters(builder, method.GetParameters());
        builder.AppendLine(") => throw new global::System.NotImplementedException();");
    }

    private static void AppendMethodModifiers(StringBuilder builder, MethodInfo method, bool declaringTypeIsInterface)
    {
        if (method.IsStatic)
        {
            builder.Append("static ");
            return;
        }
        if (declaringTypeIsInterface)
            return;
        if (method.IsAbstract)
            builder.Append("abstract ");
        else if (method.GetBaseDefinition() != method)
        {
            if (method.IsFinal)
                builder.Append("sealed ");
            builder.Append("override ");
        }
        else if (method.IsVirtual && !method.IsFinal)
            builder.Append("virtual ");
    }

    private static void AppendMethodBody(StringBuilder builder, MethodInfo method)
    {
        if (method.IsAbstract)
            builder.AppendLine(";");
        else
            builder.AppendLine(" => throw new global::System.NotImplementedException();");
    }

    private static void AppendParameters(StringBuilder builder, IReadOnlyList<ParameterInfo> parameters)
    {
        for (int i = 0; i < parameters.Count; i++)
        {
            if (i > 0)
                builder.Append(", ");
            ParameterInfo parameter = parameters[i];
            AppendFlowAttributes(builder, parameter.GetCustomAttributesData());
            if (parameter.IsDefined(typeof(ParamArrayAttribute), inherit: false))
                builder.Append("params ");
            Type parameterType = parameter.ParameterType;
            if (parameterType.IsByRef)
            {
                if (parameter.IsOut)
                    builder.Append("out ");
                else if (parameter.IsIn)
                    builder.Append("in ");
                else
                    builder.Append("ref ");
                parameterType = parameterType.GetElementType()!;
            }
            builder.Append(FormatParameterType(parameter))
                .Append(' ')
                .Append(EscapeIdentifier(parameter.Name ?? "value"));
            if (parameter.IsOptional)
                builder.Append(" = ").Append(FormatConstant(parameter.DefaultValue, parameterType));
        }
    }

    private static bool IsVisible(MethodBase? method)
        => method is not null &&
           (method.IsPublic || method.IsFamily || method.IsFamilyOrAssembly);

    private static bool IsVisible(FieldInfo field)
        => field.IsPublic || field.IsFamily || field.IsFamilyOrAssembly;

    private static string GetAccessibility(MethodBase method)
    {
        if (method.IsPublic)
            return "public";
        if (method.IsFamilyOrAssembly)
            return "protected internal";
        return "protected";
    }

    private static string GetAccessibility(FieldInfo field)
    {
        if (field.IsPublic)
            return "public";
        if (field.IsFamilyOrAssembly)
            return "protected internal";
        return "protected";
    }

    private static MethodInfo? MoreVisible(MethodInfo? first, MethodInfo? second)
    {
        if (!IsVisible(first))
            return IsVisible(second) ? second : null;
        if (!IsVisible(second))
            return first;
        return VisibilityRank(first!) >= VisibilityRank(second!) ? first : second;
    }

    private static int VisibilityRank(MethodBase method)
        => method.IsPublic ? 3 : method.IsFamilyOrAssembly ? 2 : method.IsFamily ? 1 : 0;

    private static string FormatType(Type type)
        => FormatType(type, null);

    private static string FormatParameterType(ParameterInfo parameter)
        => FormatType(parameter.ParameterType, s_nullability!.Create(parameter), new(parameter.GetCustomAttributesData(), parameter.Member));

    private static void AppendFlowAttributes(StringBuilder builder, IEnumerable<CustomAttributeData> attributes)
    {
        foreach (CustomAttributeData attribute in attributes)
        {
            if (attribute.AttributeType.Namespace != "System.Diagnostics.CodeAnalysis"
                || attribute.AttributeType.Name is not ("AllowNullAttribute" or "DisallowNullAttribute"
                    or "MaybeNullAttribute" or "NotNullAttribute" or "NotNullWhenAttribute"
                    or "MaybeNullWhenAttribute" or "NotNullIfNotNullAttribute" or "DoesNotReturnIfAttribute")) continue;
            builder.Append("[global::").Append(attribute.AttributeType.FullName).Append('(')
                .Append(string.Join(", ", attribute.ConstructorArguments.Select(static argument => FormatConstant(argument.Value, argument.ArgumentType))))
                .Append(")] ");
        }
    }

    private static string FormatType(Type type, NullabilityInfo? nullability, NullableAnnotations? annotations = null)
    {
        if (type.IsByRef || type.IsPointer)
        {
            string suffix = type.IsPointer ? "*" : string.Empty;
            return FormatType(type.GetElementType()!, nullability, annotations) + suffix;
        }
        byte flag = annotations?.Next(type) ?? 0;
        // NullabilityInfo reports an unconstrained T as nullable even when its usage is T,
        // not T?. Preserve the emitted usage flag instead of weakening delegate arguments.
        bool nullable = type.IsGenericParameter ? flag == 2 : nullability?.ReadState == NullabilityState.Nullable;
        string annotation = !type.IsValueType && nullable ? "?" : string.Empty;
        if (type.IsArray)
            return FormatType(type.GetElementType()!, nullability?.ElementType, annotations) + "[" + new string(',', type.GetArrayRank() - 1) + "]" + annotation;
        if (type.IsGenericParameter)
            return type.Name + annotation;
        if (C_TYPE_ALIASES.TryGetValue(type, out string? alias))
            return alias + annotation;
        if (!type.IsGenericType)
            return "global::" + FormatNamedTypeName(type, removeGenericArities: false) + annotation;
        Type definition = type.GetGenericTypeDefinition();
        string name = FormatNamedTypeName(definition, removeGenericArities: true);
        return "global::" + name + "<" +
               string.Join(", ", type.GetGenericArguments().Select((argument, index) =>
                   FormatType(argument, nullability?.GenericTypeArguments.ElementAtOrDefault(index), annotations))) + ">" + annotation;
    }

    private sealed class NullableAnnotations
    {
        private readonly byte[] m_flags;
        private readonly byte m_context;
        private int m_index;

        internal NullableAnnotations(IEnumerable<CustomAttributeData> attributes, MemberInfo owner)
        {
            CustomAttributeData? transform = attributes.FirstOrDefault(static attribute =>
                attribute.AttributeType.FullName == "System.Runtime.CompilerServices.NullableAttribute");
            m_flags = transform?.ConstructorArguments[0].Value switch
            {
                byte flag => [flag],
                IEnumerable<CustomAttributeTypedArgument> flags => flags.Select(static value => (byte)value.Value!).ToArray(),
                _ => []
            };
            for (MemberInfo? current = owner; current is not null; current = current.DeclaringType)
            {
                CustomAttributeData? context = current.GetCustomAttributesData().FirstOrDefault(static attribute =>
                    attribute.AttributeType.FullName == "System.Runtime.CompilerServices.NullableContextAttribute");
                if (context is null) continue;
                m_context = (byte)context.ConstructorArguments[0].Value!;
                break;
            }
        }

        internal byte Next(Type type)
        {
            if (type.IsValueType && !type.IsGenericType) return 0;
            int index = m_index++;
            return index < m_flags.Length ? m_flags[index] : m_context;
        }
    }

    private static string FormatNamedTypeName(Type type, bool removeGenericArities)
    {
        string implementationNamespace = type.Namespace ?? string.Empty;
        if (s_typeNames is not null && s_typeNames.TryGetValue(type, out string? typeName))
        {
            string aliasNamespace = ResolveNamespace(implementationNamespace);
            return string.IsNullOrEmpty(aliasNamespace)
                ? typeName
                : aliasNamespace + "." + typeName;
        }
        string fullName = type.FullName ?? type.Name;
        string relativeName = string.IsNullOrEmpty(implementationNamespace)
            ? fullName
            : fullName[(implementationNamespace.Length + 1)..];
        if (removeGenericArities)
            relativeName = RemoveGenericArities(relativeName);
        relativeName = relativeName.Replace('+', '.');
        string targetNamespace = ResolveNamespace(implementationNamespace);
        return string.IsNullOrEmpty(targetNamespace)
            ? relativeName
            : targetNamespace + "." + relativeName;
    }

    private static string ResolveNamespace(string implementationNamespace)
        => s_namespaceMappings is not null &&
           s_namespaceMappings.TryGetValue(implementationNamespace, out string? apiNamespace)
            ? apiNamespace
            : implementationNamespace;

    private static string GetTypeName(Type type)
        => s_typeNames is not null && s_typeNames.TryGetValue(type, out string? name)
            ? name
            : RemoveArity(type.Name);

    private static bool IsApiMethod(MethodInfo method)
    {
        if (!IsApiType(method.ReturnType) || !AreApiParameters(method.GetParameters()))
            return false;
        return method.GetGenericArguments()
            .SelectMany(static argument => argument.GetGenericParameterConstraints())
            .All(IsApiType);
    }

    private static bool AreApiParameters(IEnumerable<ParameterInfo> parameters)
        => parameters.All(static parameter => IsApiType(parameter.ParameterType));

    private static bool IsApiType(Type type)
    {
        if (type.IsByRef || type.IsPointer || type.IsArray)
            return IsApiType(type.GetElementType()!);
        if (type.IsGenericParameter)
            return type.GetGenericParameterConstraints().All(IsApiType);
        if (C_TYPE_ALIASES.ContainsKey(type) || type == typeof(void))
            return true;
        if (type.IsGenericType)
        {
            return IsApiNamedType(type.GetGenericTypeDefinition()) &&
                   type.GetGenericArguments().All(IsApiType);
        }
        return IsApiNamedType(type);
    }

    private static void RejectUnclosedMember(MemberInfo member, Type dependency)
        => RejectUnclosedMember(member, new[] { dependency });

    private static void RejectUnclosedMember(MemberInfo member, IEnumerable<Type> dependencies)
    {
        if (member.IsDefined(typeof(ScriptingApiIgnoreAttribute), inherit: false))
            return;
        string missing = string.Join(
            ", ",
            dependencies
                .SelectMany(GetUnexportedTypes)
                .Select(static type => type.FullName ?? type.Name)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(static name => name, StringComparer.Ordinal));
        throw new InvalidOperationException(
            $"Scripting API member '{member.DeclaringType?.FullName}.{member.Name}' depends on " +
            $"unexported type(s): {missing}. Export the dependency or mark the member with " +
            $"{nameof(ScriptingApiIgnoreAttribute)}.");
    }

    private static IEnumerable<Type> GetUnexportedTypes(Type type)
    {
        if (type.IsByRef || type.IsPointer || type.IsArray)
        {
            foreach (Type missing in GetUnexportedTypes(type.GetElementType()!))
                yield return missing;
            yield break;
        }
        if (type.IsGenericParameter)
        {
            foreach (Type constraint in type.GetGenericParameterConstraints())
            foreach (Type missing in GetUnexportedTypes(constraint))
                yield return missing;
            yield break;
        }
        if (C_TYPE_ALIASES.ContainsKey(type) || type == typeof(void))
            yield break;
        if (type.IsGenericType)
        {
            if (!IsApiNamedType(type.GetGenericTypeDefinition()))
                yield return type.GetGenericTypeDefinition();
            foreach (Type argument in type.GetGenericArguments())
            foreach (Type missing in GetUnexportedTypes(argument))
                yield return missing;
            yield break;
        }
        if (!IsApiNamedType(type))
            yield return type;
    }

    private static bool IsApiNamedType(Type type)
    {
        Assembly assembly = type.Assembly;
        string name = assembly.GetName().Name ?? string.Empty;
        if (assembly == typeof(object).Assembly ||
            name.StartsWith("System.", StringComparison.Ordinal) ||
            name.StartsWith("Microsoft.", StringComparison.Ordinal))
        {
            return true;
        }
        return s_exportedTypes?.Contains(type) == true;
    }

    private static string FormatConstant(object? value, Type type)
    {
        if (value is null || value == DBNull.Value || value == Missing.Value)
            return "default";
        if (type.IsEnum)
        {
            object numeric = Convert.ChangeType(
                value,
                Enum.GetUnderlyingType(type),
                CultureInfo.InvariantCulture);
            return "(" + FormatType(type) + ")" + FormatNumericConstant(numeric);
        }
        return value switch
        {
            string text => "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"",
            char character => "'" + (character == '\'' ? "\\'" : character.ToString()) + "'",
            bool boolean => boolean ? "true" : "false",
            float number => number.ToString("R", CultureInfo.InvariantCulture) + "F",
            double number => number.ToString("R", CultureInfo.InvariantCulture) + "D",
            decimal number => number.ToString(CultureInfo.InvariantCulture) + "M",
            _ => FormatNumericConstant(value)
        };
    }

    private static string FormatNumericConstant(object value)
        => Convert.ToString(value, CultureInfo.InvariantCulture) ?? "0";

    private static bool TryGetOperator(string name, out string? symbol)
    {
        symbol = name switch
        {
            "op_Addition" => "+",
            "op_Subtraction" => "-",
            "op_Multiply" => "*",
            "op_Division" => "/",
            "op_Modulus" => "%",
            "op_Equality" => "==",
            "op_Inequality" => "!=",
            "op_LessThan" => "<",
            "op_GreaterThan" => ">",
            "op_LessThanOrEqual" => "<=",
            "op_GreaterThanOrEqual" => ">=",
            "op_UnaryNegation" => "-",
            "op_UnaryPlus" => "+",
            "op_Increment" => "++",
            "op_Decrement" => "--",
            "op_BitwiseAnd" => "&",
            "op_BitwiseOr" => "|",
            "op_ExclusiveOr" => "^",
            "op_OnesComplement" => "~",
            "op_LeftShift" => "<<",
            "op_RightShift" => ">>",
            "op_True" => "true",
            "op_False" => "false",
            _ => null
        };
        return symbol is not null;
    }

    private static string EscapeIdentifier(string value)
        => C_KEYWORDS.Contains(value) ? "@" + value : value;

    private static string RemoveArity(string value)
    {
        int separator = value.IndexOf('`');
        return separator < 0 ? value : value[..separator];
    }

    private static string RemoveGenericArities(string value)
    {
        var builder = new StringBuilder(value.Length);
        for (int i = 0; i < value.Length; i++)
        {
            if (value[i] != '`')
            {
                builder.Append(value[i]);
                continue;
            }
            while (i + 1 < value.Length && char.IsDigit(value[i + 1]))
                i++;
        }
        return builder.ToString();
    }

    private static bool IsStaticClass(this Type type) => type.IsAbstract && type.IsSealed;

    private static readonly HashSet<string> C_KEYWORDS = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while"
    };

    private static readonly IReadOnlyDictionary<Type, string> C_TYPE_ALIASES =
        new Dictionary<Type, string>
        {
            [typeof(void)] = "void",
            [typeof(bool)] = "bool",
            [typeof(byte)] = "byte",
            [typeof(sbyte)] = "sbyte",
            [typeof(short)] = "short",
            [typeof(ushort)] = "ushort",
            [typeof(int)] = "int",
            [typeof(uint)] = "uint",
            [typeof(long)] = "long",
            [typeof(ulong)] = "ulong",
            [typeof(char)] = "char",
            [typeof(float)] = "float",
            [typeof(double)] = "double",
            [typeof(decimal)] = "decimal",
            [typeof(string)] = "string",
            [typeof(object)] = "object"
        };
}
