<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../core/Inno.Core.Execution/Inno.Core.Execution.csproj" PrivateAssets="compile" />
    <ProjectReference
      Include="../Inno.Extensibility.Modules/Inno.Extensibility.Modules.csproj"
      PrivateAssets="compile" />
    <ProjectReference Include="../../scripting/Inno.Scripting.Api/Inno.Scripting.Api.csproj" PrivateAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Inno.Extensibility.Catalogs/Inno.Extensibility.Catalogs.csproj" />
  </ItemGroup>
</Project>
