<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1572;CS1573;CS1591</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\common\Inno.Adapter\Inno.Adapter.csproj" />
    <ProjectReference Include="..\..\audio\Inno.Adapter.Audio.MiniAudio\Inno.Adapter.Audio.MiniAudio.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\input\Inno.Adapter.Input.Sdl3\Inno.Adapter.Input.Sdl3.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\platform\Inno.Adapter.Platform.Sdl3\Inno.Adapter.Platform.Sdl3.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\rendering\Inno.Adapter.Rendering.Bgfx\Inno.Adapter.Rendering.Bgfx.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\storage\Inno.Adapter.Storage.FileSystem\Inno.Adapter.Storage.FileSystem.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\text\Inno.Adapter.Text.FreeTypeHarfBuzz\Inno.Adapter.Text.FreeTypeHarfBuzz.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\ui\Inno.Adapter.UI.RmlUi\Inno.Adapter.UI.RmlUi.csproj" PrivateAssets="compile" />
    <ProjectReference Include="..\..\text\Inno.Adapter.Text\Inno.Adapter.Text.csproj" />
    <ProjectReference Include="..\..\ui\Inno.Adapter.UI\Inno.Adapter.UI.csproj" />
    <ProjectReference Include="..\..\..\services\text\Inno.Text\Inno.Text.csproj" />
    <ProjectReference Include="..\..\..\services\ui\Inno.UI\Inno.UI.csproj" />
  </ItemGroup>
</Project>
