using Inno.Scripting.Api;
using Inno.UI;

[assembly: ScriptingApiNamespace("InnoEngine.UI", "Inno.UI", ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UI), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiExecutionContext), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IUiService), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiContextHandle), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiDocumentHandle), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiContextOptions), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiDocumentLanguageId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiDocumentSource), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiDocumentFragment), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiDocumentAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiDocumentFontFace), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiTextureData), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiEventType), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiEvent), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiMeshHandle), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiTextureHandle), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiVertex), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiClipRectangle), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiDrawCommand), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiMeshUpdate), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiTextureUpdate), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiRenderFrame), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(UiInputSnapshot), ScriptingApiScope.Runtime)]
