<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <InnoGeneratePlayerComposition>true</InnoGeneratePlayerComposition>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Inno.Player</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../foundation/core/Inno.Core.Execution/Inno.Core.Execution.csproj" />
    <ProjectReference Include="../Inno.Player.Runtime/Inno.Player.Runtime.csproj" />
    <ProjectReference Include="../../../adapters/default/Inno.Adapter.Default/Inno.Adapter.Default.csproj" />
    <ProjectReference Include="../../../adapters/content/Inno.Adapter.Content.FileSystem/Inno.Adapter.Content.FileSystem.csproj" />
    <ProjectReference Include="../../../adapters/storage/Inno.Adapter.Storage.FileSystem/Inno.Adapter.Storage.FileSystem.csproj" />
  </ItemGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="InnoGeneratePlayerComposition" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../foundation/extensibility/Inno.Extensibility.Catalogs/Inno.Extensibility.Catalogs.csproj" />
  </ItemGroup>
</Project>
