<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Inno.Player</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Inno.Player.Runtime/Inno.Player.Runtime.csproj" />
    <ProjectReference Include="../../../adapters/default/Inno.Adapter.Default/Inno.Adapter.Default.csproj" />
  </ItemGroup>
</Project>
