using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Inno.Tooling.Architecture;

internal static class PublicApiDocumenter
{
    internal static int Document(string repositoryRoot, IReadOnlyList<string> roots)
    {
        int changedFileCount = 0;
        foreach (string rootName in roots)
        {
            if (string.Equals(rootName, "tools", StringComparison.Ordinal))
            {
                continue;
            }
            string root = Path.Combine(repositoryRoot, rootName);
            if (!Directory.Exists(root))
                continue;
            foreach (string path in Directory.EnumerateFiles(root, "*.cs", SearchOption.AllDirectories))
            {
                if (path.Contains($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}", StringComparison.Ordinal) ||
                    path.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}", StringComparison.Ordinal))
                {
                    continue;
                }
                string source = File.ReadAllText(path);
                if (source.Contains("<auto-generated>", StringComparison.OrdinalIgnoreCase) ||
                    source.Contains("[GeneratedCode", StringComparison.Ordinal))
                {
                    continue;
                }
                SyntaxTree tree = CSharpSyntaxTree.ParseText(source, path: path);
                SyntaxNode rootNode = tree.GetRoot();
                SyntaxNode rewritten = new DocumentationRewriter().Visit(rootNode)!;
                string updated = rewritten.ToFullString();
                if (string.Equals(source, updated, StringComparison.Ordinal))
                    continue;
                File.WriteAllText(path, updated);
                changedFileCount++;
            }
        }
        return changedFileCount;
    }

    private sealed class DocumentationRewriter : CSharpSyntaxRewriter
    {
        public override SyntaxNode? VisitClassDeclaration(ClassDeclarationSyntax node)
            => DocumentType((ClassDeclarationSyntax)base.VisitClassDeclaration(node)!);

        public override SyntaxNode? VisitStructDeclaration(StructDeclarationSyntax node)
            => DocumentType((StructDeclarationSyntax)base.VisitStructDeclaration(node)!);

        public override SyntaxNode? VisitInterfaceDeclaration(InterfaceDeclarationSyntax node)
            => DocumentType((InterfaceDeclarationSyntax)base.VisitInterfaceDeclaration(node)!);

        public override SyntaxNode? VisitRecordDeclaration(RecordDeclarationSyntax node)
            => DocumentType((RecordDeclarationSyntax)base.VisitRecordDeclaration(node)!);

        public override SyntaxNode? VisitEnumDeclaration(EnumDeclarationSyntax node)
            => DocumentType((EnumDeclarationSyntax)base.VisitEnumDeclaration(node)!);

        public override SyntaxNode? VisitDelegateDeclaration(DelegateDeclarationSyntax node)
        {
            node = (DelegateDeclarationSyntax)base.VisitDelegateDeclaration(node)!;
            return ShouldDocument(node)
                ? AddDocumentation(node, DescribeDelegate(node), node.ParameterList.Parameters, node.TypeParameterList, node.ReturnType)
                : node;
        }

        public override SyntaxNode? VisitEnumMemberDeclaration(EnumMemberDeclarationSyntax node)
        {
            node = (EnumMemberDeclarationSyntax)base.VisitEnumMemberDeclaration(node)!;
            if (node.Parent is not EnumDeclarationSyntax parent || !ShouldDocument(parent))
                return node;
            return AddDocumentation(node, DescribeEnumMember(node.Identifier.ValueText));
        }

        public override SyntaxNode? VisitConstructorDeclaration(ConstructorDeclarationSyntax node)
        {
            node = (ConstructorDeclarationSyntax)base.VisitConstructorDeclaration(node)!;
            return ShouldDocument(node)
                ? AddDocumentation(node, DescribeConstructor(node), node.ParameterList.Parameters)
                : node;
        }

        public override SyntaxNode? VisitMethodDeclaration(MethodDeclarationSyntax node)
        {
            node = (MethodDeclarationSyntax)base.VisitMethodDeclaration(node)!;
            return ShouldDocument(node)
                ? AddDocumentation(
                    node,
                    DescribeMethod(node.Identifier.ValueText, node.Parent),
                    node.ParameterList.Parameters,
                    node.TypeParameterList,
                    node.ReturnType)
                : node;
        }

        public override SyntaxNode? VisitOperatorDeclaration(OperatorDeclarationSyntax node)
        {
            node = (OperatorDeclarationSyntax)base.VisitOperatorDeclaration(node)!;
            return ShouldDocument(node)
                ? AddDocumentation(node, DescribeOperator(node.OperatorToken.ValueText), node.ParameterList.Parameters, returnType: node.ReturnType)
                : node;
        }

        public override SyntaxNode? VisitConversionOperatorDeclaration(ConversionOperatorDeclarationSyntax node)
        {
            node = (ConversionOperatorDeclarationSyntax)base.VisitConversionOperatorDeclaration(node)!;
            return ShouldDocument(node)
                ? AddDocumentation(
                    node,
                    $"Converts the supplied value to <see cref=\"{EscapeType(node.Type)}\"/>.",
                    node.ParameterList.Parameters,
                    returnType: node.Type)
                : node;
        }

        public override SyntaxNode? VisitPropertyDeclaration(PropertyDeclarationSyntax node)
        {
            node = (PropertyDeclarationSyntax)base.VisitPropertyDeclaration(node)!;
            return ShouldDocument(node)
                ? AddDocumentation(node, DescribeProperty(node.Identifier.ValueText, node.Type))
                : node;
        }

        public override SyntaxNode? VisitIndexerDeclaration(IndexerDeclarationSyntax node)
        {
            node = (IndexerDeclarationSyntax)base.VisitIndexerDeclaration(node)!;
            return ShouldDocument(node)
                ? AddDocumentation(node, "Gets or sets the value identified by the supplied index.", node.ParameterList.Parameters)
                : node;
        }

        public override SyntaxNode? VisitEventDeclaration(EventDeclarationSyntax node)
        {
            node = (EventDeclarationSyntax)base.VisitEventDeclaration(node)!;
            return ShouldDocument(node)
                ? AddDocumentation(node, DescribeEvent(node.Identifier.ValueText))
                : node;
        }

        public override SyntaxNode? VisitEventFieldDeclaration(EventFieldDeclarationSyntax node)
        {
            node = (EventFieldDeclarationSyntax)base.VisitEventFieldDeclaration(node)!;
            if (!ShouldDocument(node))
                return node;
            string name = node.Declaration.Variables.FirstOrDefault()?.Identifier.ValueText ?? "state";
            return AddDocumentation(node, DescribeEvent(name));
        }

        public override SyntaxNode? VisitFieldDeclaration(FieldDeclarationSyntax node)
        {
            node = (FieldDeclarationSyntax)base.VisitFieldDeclaration(node)!;
            if (!ShouldDocument(node))
                return node;
            string name = node.Declaration.Variables.FirstOrDefault()?.Identifier.ValueText ?? "value";
            return AddDocumentation(node, DescribeField(name));
        }

        private static T DocumentType<T>(T node)
            where T : TypeDeclarationSyntax
        {
            if (!ShouldDocument(node))
                return node;
            SeparatedSyntaxList<ParameterSyntax> parameters = node switch
            {
                ClassDeclarationSyntax declaration when declaration.ParameterList is not null => declaration.ParameterList.Parameters,
                StructDeclarationSyntax declaration when declaration.ParameterList is not null => declaration.ParameterList.Parameters,
                RecordDeclarationSyntax record when record.ParameterList is not null => record.ParameterList.Parameters,
                _ => default
            };
            return AddDocumentation(node, DescribeType(node.Identifier.ValueText, node), parameters, node.TypeParameterList);
        }

        private static EnumDeclarationSyntax DocumentType(EnumDeclarationSyntax node)
            => ShouldDocument(node)
                ? AddDocumentation(node, DescribeType(node.Identifier.ValueText, node))
                : node;

        private static bool ShouldDocument(MemberDeclarationSyntax node)
        {
            if (HasDocumentation(node))
                return true;
            return RequiresDocumentation(node);
        }

        private static bool RequiresDocumentation(MemberDeclarationSyntax node)
        {
            if (node.Parent is InterfaceDeclarationSyntax)
                return true;
            return node.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.PublicKeyword)) ||
                   node.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.ProtectedKeyword));
        }

        private static bool HasDocumentation(SyntaxNode node)
            => node.GetLeadingTrivia().Any(static trivia => trivia.GetStructure() is DocumentationCommentTriviaSyntax);

        private static T AddDocumentation<T>(
            T node,
            string summary,
            SeparatedSyntaxList<ParameterSyntax> parameters = default,
            TypeParameterListSyntax? typeParameters = null,
            TypeSyntax? returnType = null)
            where T : MemberDeclarationSyntax
        {
            if (HasDocumentation(node))
            {
                string existing = node.GetLeadingTrivia().ToFullString();
                if (!RequiresDocumentation(node) && ContainsGeneratedFallback(existing))
                    return RemoveDocumentation(node);
                return RewriteGenericDocumentation(node, summary, parameters, typeParameters, returnType);
            }
            string indentation = GetIndentation(node);
            var builder = new StringBuilder();
            AppendElement(builder, indentation, "summary", summary);
            if (typeParameters is not null)
            {
                foreach (TypeParameterSyntax parameter in typeParameters.Parameters)
                {
                    AppendElement(
                        builder,
                        indentation,
                        $"typeparam name=\"{parameter.Identifier.ValueText}\"",
                        $"The caller-selected {Humanize(parameter.Identifier.ValueText)} type whose declared constraints are enforced by this operation.",
                        "typeparam");
                }
            }
            foreach (ParameterSyntax parameter in parameters)
            {
                string name = parameter.Identifier.ValueText;
                AppendElement(
                    builder,
                    indentation,
                    $"param name=\"{name}\"",
                    DescribeParameter(parameter, GetOperationName(node)),
                    "param");
            }
            if (returnType is not null && !string.Equals(returnType.ToString(), "void", StringComparison.Ordinal))
            {
                AppendElement(builder, indentation, "returns", DescribeReturn(GetOperationName(node), returnType));
            }
            SyntaxTriviaList documentation = SyntaxFactory.ParseLeadingTrivia(builder.ToString());
            SyntaxTriviaList leading = node.GetLeadingTrivia();
            while (leading.Count > 0 && leading[^1].IsKind(SyntaxKind.WhitespaceTrivia))
                leading = leading.RemoveAt(leading.Count - 1);
            return node.WithLeadingTrivia(leading.AddRange(documentation));
        }

        private static T RemoveDocumentation<T>(T node)
            where T : SyntaxNode
        {
            SyntaxTriviaList leading = SyntaxFactory.TriviaList(node.GetLeadingTrivia().Where(
                static trivia => trivia.GetStructure() is not DocumentationCommentTriviaSyntax));
            return node.WithLeadingTrivia(leading);
        }

        private static T RewriteGenericDocumentation<T>(
            T node,
            string summary,
            SeparatedSyntaxList<ParameterSyntax> parameters,
            TypeParameterListSyntax? typeParameters,
            TypeSyntax? returnType)
            where T : SyntaxNode
        {
            string leading = node.GetLeadingTrivia().ToFullString();
            if (!ContainsPlaceholder(leading))
                return node;
            string newline = leading.Contains("\r\n", StringComparison.Ordinal) ? "\r\n" : "\n";
            string rewritten = RewriteElement(leading, "summary", null, summary, newline);
            foreach (ParameterSyntax parameter in parameters)
            {
                string name = parameter.Identifier.ValueText;
                rewritten = RewriteElement(
                    rewritten,
                    "param",
                    name,
                    DescribeParameter(parameter, GetOperationName(node)),
                    newline);
            }
            if (typeParameters is not null)
            {
                foreach (TypeParameterSyntax parameter in typeParameters.Parameters)
                {
                    string name = parameter.Identifier.ValueText;
                    rewritten = RewriteElement(
                        rewritten,
                        "typeparam",
                        name,
                        $"The caller-selected {Humanize(name)} type whose declared constraints are enforced by this operation.",
                        newline);
                }
            }
            if (returnType is not null && !string.Equals(returnType.ToString(), "void", StringComparison.Ordinal))
            {
                rewritten = RewriteElement(
                    rewritten,
                    "returns",
                    null,
                    DescribeReturn(GetOperationName(node), returnType),
                    newline);
            }
            else if (node is BaseTypeDeclarationSyntax or ConstructorDeclarationSyntax)
            {
                rewritten = RemoveElement(rewritten, "returns", null, newline);
            }
            return node.WithLeadingTrivia(SyntaxFactory.ParseLeadingTrivia(rewritten));
        }

        private static string RewriteElement(
            string documentation,
            string element,
            string? name,
            string replacement,
            string newline)
        {
            string opening = name is null
                ? $"/// <{element}>"
                : $"/// <{element} name=\"{name}\">";
            string closing = $"/// </{element}>";
            List<string> lines = documentation.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n').ToList();
            for (int index = 0; index < lines.Count; index++)
            {
                if (!string.Equals(lines[index].TrimStart(), opening, StringComparison.Ordinal))
                    continue;
                int end = index + 1;
                while (end < lines.Count && !string.Equals(lines[end].TrimStart(), closing, StringComparison.Ordinal))
                    end++;
                if (end >= lines.Count)
                    return documentation;
                string content = string.Join('\n', lines.Skip(index + 1).Take(end - index - 1));
                if (!ContainsPlaceholder(content))
                    return documentation;
                string indentation = lines[index][..^lines[index].TrimStart().Length];
                lines.RemoveRange(index + 1, end - index - 1);
                lines.Insert(index + 1, $"{indentation}/// {replacement}");
                return string.Join(newline, lines);
            }
            return documentation;
        }

        private static string RemoveElement(
            string documentation,
            string element,
            string? name,
            string newline)
        {
            string opening = name is null
                ? $"/// <{element}>"
                : $"/// <{element} name=\"{name}\">";
            string closing = $"/// </{element}>";
            List<string> lines = documentation.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n').ToList();
            for (int index = 0; index < lines.Count; index++)
            {
                if (!string.Equals(lines[index].TrimStart(), opening, StringComparison.Ordinal))
                    continue;
                int end = index + 1;
                while (end < lines.Count && !string.Equals(lines[end].TrimStart(), closing, StringComparison.Ordinal))
                    end++;
                if (end >= lines.Count)
                    return documentation;
                lines.RemoveRange(index, end - index + 1);
                return string.Join(newline, lines);
            }
            return documentation;
        }

        private static bool ContainsPlaceholder(string documentation)
            => documentation.Contains("operation defined by this contract", StringComparison.Ordinal)
               || documentation.Contains("operation required by the implemented contract", StringComparison.Ordinal)
               || documentation.Contains("exposed by this contract", StringComparison.Ordinal)
               || documentation.Contains("exposed by this implementation", StringComparison.Ordinal)
               || documentation.Contains("supplied to this operation", StringComparison.Ordinal)
               || documentation.Contains("processed by the operation", StringComparison.Ordinal)
               || documentation.Contains("processed by this operation", StringComparison.Ordinal)
               || documentation.Contains("produced by the operation", StringComparison.Ordinal)
               || documentation.Contains("produced by this implementation", StringComparison.Ordinal)
               || documentation.Contains("Creates a new instance with the supplied state", StringComparison.Ordinal)
               || documentation.Contains("type used by this contract", StringComparison.Ordinal)
               || documentation.Contains("associated with the current instance", StringComparison.Ordinal)
               || documentation.Contains("represented by the supplied inputs", StringComparison.Ordinal)
               || documentation.Contains("result from validated inputs", StringComparison.Ordinal)
               || documentation.Contains("behavior while preserving this instance's invariants", StringComparison.Ordinal)
               || documentation.Contains("Executes this contract at the caller-controlled boundary", StringComparison.Ordinal)
               || documentation.Contains("Transforms validated inputs into a deterministic result", StringComparison.Ordinal)
               || documentation.Contains(" input consumed by this operation", StringComparison.Ordinal)
               || documentation.Contains("Gets caller-visible ", StringComparison.Ordinal)
               || documentation.Contains("state exposed by this contract", StringComparison.Ordinal)
               || documentation.Contains("value associated with this contract", StringComparison.Ordinal)
               || documentation.Contains("type accepted by this API boundary", StringComparison.Ordinal)
               || documentation.Contains("The caller-provided <paramref", StringComparison.Ordinal)
               || documentation.Contains("value owned by the current instance", StringComparison.Ordinal)
               || documentation.Contains("Models the ", StringComparison.Ordinal)
               || documentation.Contains("Runs the ", StringComparison.Ordinal)
               || documentation.Contains("Performs the requested operation against the supplied context", StringComparison.Ordinal)
               || documentation.Contains("Performs the ", StringComparison.Ordinal)
               || documentation.Contains("required to ", StringComparison.Ordinal)
               || documentation.Contains("changes changes", StringComparison.Ordinal);

        private static bool ContainsGeneratedFallback(string documentation)
            => documentation.Contains("Executes this contract at the caller-controlled boundary", StringComparison.Ordinal)
               || documentation.Contains("Transforms validated inputs into a deterministic result", StringComparison.Ordinal)
               || documentation.Contains(" input consumed by this operation", StringComparison.Ordinal)
               || documentation.Contains("Gets caller-visible ", StringComparison.Ordinal)
               || documentation.Contains("associated with the current instance", StringComparison.Ordinal)
               || documentation.Contains("represented by the supplied inputs", StringComparison.Ordinal)
               || documentation.Contains("result from validated inputs", StringComparison.Ordinal);

        private static string GetOperationName(SyntaxNode node)
            => node switch
            {
                MethodDeclarationSyntax method => method.Identifier.ValueText,
                ConstructorDeclarationSyntax constructor => constructor.Identifier.ValueText,
                DelegateDeclarationSyntax callback => callback.Identifier.ValueText,
                OperatorDeclarationSyntax operation => operation.OperatorToken.ValueText,
                ConversionOperatorDeclarationSyntax => "Convert",
                _ => "operation"
            };

        private static void AppendElement(
            StringBuilder builder,
            string indentation,
            string opening,
            string content,
            string? closing = null)
        {
            builder.Append(indentation).Append("/// <").Append(opening).AppendLine(">");
            builder.Append(indentation).Append("/// ").AppendLine(content);
            builder.Append(indentation).Append("/// </").Append(closing ?? opening).AppendLine(">");
        }

        private static string GetIndentation(SyntaxNode node)
        {
            SyntaxTrivia whitespace = node.GetLeadingTrivia()
                .LastOrDefault(static trivia => trivia.IsKind(SyntaxKind.WhitespaceTrivia));
            return whitespace.ToString();
        }

        private static string DescribeType(string name, BaseTypeDeclarationSyntax node)
        {
            if (name == "KeyCode")
                return "Represents a backend-neutral physical key used by runtime input and editor shortcut contracts.";
            if (name.StartsWith("Vector", StringComparison.Ordinal))
                return $"Represents a mutable {Humanize(name)} value with component-wise arithmetic semantics.";
            if (name is "Rect" or "RectInt")
                return $"Represents an axis-aligned {Humanize(name)} defined by position and size.";
            if (name == "Matrix")
                return "Represents a mutable four-by-four transformation matrix using the engine coordinate convention.";
            if (name == "Quaternion")
                return "Represents a rotation as a normalized four-component quaternion.";
            if (name == "Color")
                return "Represents a linear red, green, blue, and alpha color value.";
            if (name is "ImGui" or "ImGuiP" or "ImGuiConfig")
                return "Provides the generated native Dear ImGui ABI surface used exclusively by the platform adapter.";
            if (name is "ImGuizmo" or "ImGuizmoConfig")
                return "Provides the generated native ImGuizmo ABI surface used exclusively by the editor adapter.";
            if (name == "SDL")
                return "Provides the generated SDL3 ABI surface used exclusively by the SDL platform adapter.";
            if (name.EndsWith("Ptr", StringComparison.Ordinal) || name.EndsWith("PtrPtr", StringComparison.Ordinal))
                return $"Wraps an opaque native {Humanize(name)} pointer without taking ownership of the referenced allocation.";
            if (name is "Point32")
                return "Represents an integer native point exchanged with the SDL3 ABI.";
            if (name is "Msg")
                return "Carries a native platform message through the SDL3 event ABI.";
            if (name is "RenderShaderPassArtifact")
                return "Carries one immutable compiled shader pass and its reflected runtime bindings.";
            if (name is "BgfxDevice")
                return "Implements the backend-neutral render device contract using generation-scoped BGFX resources.";
            if (node is InterfaceDeclarationSyntax)
                return $"Defines the {Humanize(name)} contract implemented across module boundaries.";
            if (node is EnumDeclarationSyntax)
                return $"Identifies the supported {Humanize(name)} values for this contract.";
            return name switch
            {
                _ when name.EndsWith("Options", StringComparison.Ordinal) || name.EndsWith("Settings", StringComparison.Ordinal) =>
                    $"Collects the validated {Humanize(name)} values that configure one owned operation.",
                _ when name.EndsWith("Request", StringComparison.Ordinal) =>
                    $"Carries the immutable inputs required to execute one {Humanize(name[..^"Request".Length])} request.",
                _ when name.EndsWith("Result", StringComparison.Ordinal) =>
                    $"Describes the completed outcome of one {Humanize(name[..^"Result".Length])} operation.",
                _ when name.EndsWith("Descriptor", StringComparison.Ordinal) || name.EndsWith("Description", StringComparison.Ordinal) =>
                    $"Describes the backend-neutral {Humanize(name)} data exchanged across subsystem boundaries.",
                _ when name.EndsWith("Snapshot", StringComparison.Ordinal) =>
                    $"Provides an immutable {Humanize(name)} view captured from one active generation.",
                _ when name.EndsWith("Handle", StringComparison.Ordinal) || name.EndsWith("Id", StringComparison.Ordinal) =>
                    $"Identifies one {Humanize(name)} value without exposing its implementation storage.",
                _ when name.EndsWith("Context", StringComparison.Ordinal) =>
                    $"Provides operation-scoped {Humanize(name)} services and state without transferring their ownership.",
                _ when name.EndsWith("Exception", StringComparison.Ordinal) =>
                    $"Reports a failure that prevents the {Humanize(name[..^"Exception".Length])} contract from completing.",
                _ => $"Models the {Humanize(name)} domain value and its caller-visible invariants."
            };
        }

        private static string DescribeDelegate(DelegateDeclarationSyntax node)
            => $"Handles the {Humanize(node.Identifier.ValueText)} callback with the supplied context.";

        private static string DescribeConstructor(ConstructorDeclarationSyntax node)
            => node.Identifier.ValueText.StartsWith("Vector", StringComparison.Ordinal)
                ? "Creates a vector from explicit component values."
                : $"Creates a validated {Humanize(node.Identifier.ValueText)} instance.";

        private static string DescribeMethod(string name, SyntaxNode? parent)
            => name switch
            {
                "Length" => "Calculates the Euclidean magnitude of this value.",
                "LengthSquared" => "Calculates the squared Euclidean magnitude without a square-root operation.",
                "Normalize" or "NormalizeSafe" => "Returns a unit-length value while handling degenerate input according to the method contract.",
                "Dot" => "Calculates the scalar dot product of two values.",
                "Cross" => "Calculates the vector perpendicular to both supplied vectors.",
                "Angle" => "Calculates the unsigned angle in radians between two values.",
                "SignedAngle" => "Calculates the signed angle in radians from one value to another.",
                "Project" or "ProjectToVector3" => "Projects the supplied value onto the requested dimensional space.",
                "Lerp" => "Interpolates linearly between two values without clamping the interpolation factor.",
                "Min" => "Selects the minimum value independently for each component.",
                "Max" => "Selects the maximum value independently for each component.",
                "Reflect" => "Reflects an incident value across the supplied normal.",
                "Transform" => "Transforms the supplied value by the requested transformation.",
                "Equals" => "Determines whether this value and the supplied value represent the same logical state.",
                "GetHashCode" => "Computes a hash code consistent with the implemented equality contract.",
                "ToString" => "Formats this value as a human-readable component list.",
                "Dispose" => "Releases the resources owned by this instance.",
                "OnStart" => "Initializes this feature after its owning runtime has activated all required services.",
                "OnStop" => "Stops this feature before its owning runtime releases generation-scoped services.",
                "OnUpdate" => "Advances this feature once using the current editor or runtime frame state.",
                "OnLateUpdate" => "Completes frame work that must run after normal update processing.",
                "OnDraw" => "Renders this feature using the current editor presentation context.",
                "OnDispose" => "Releases resources retained by this feature after it has stopped.",
                "Main" => "Runs the command-line entry point and returns a process exit code.",
                "Report" => "Publishes one progress update to the receiving workflow.",
                "Validate" or "ValidateSource" or "ValidateSubmodules" =>
                    "Validates the supplied input and rejects state that cannot satisfy this contract.",
                "Parse" => "Parses validated input into the strongly typed state required by the caller.",
                "Build" => "Builds a validated result from the current immutable input snapshot.",
                "Compile" or "CompileAsync" or "CompileKtxAsync" =>
                    "Compiles the supplied source into a validated runtime artifact.",
                "IsSupported" => "Determines whether the current host can execute this implementation.",
                "OnEnable" => "Runs immediately after this behavior becomes active and enabled.",
                "OnDisable" => "Runs immediately before this behavior stops being active and enabled.",
                "OnAttach" => "Attaches this feature to its owning runtime generation.",
                "OnDetach" => "Detaches this feature and releases generation-scoped state.",
                "OnBeforeRender" => "Prepares frame-scoped state before render requests are submitted.",
                "OnRender" => "Submits render work for the current frame.",
                "OnAfterRender" => "Completes the current render frame and releases frame-scoped state.",
                "BeginFrame" => "Begins a frame-scoped operation and makes queued work visible.",
                "EndFrame" => "Commits the current frame-scoped operation and returns its completion identity.",
                "Load" or "LoadAsync" => "Loads and validates the requested value from its configured source.",
                "Save" or "SaveAsync" => "Persists the supplied value through the configured storage contract.",
                "Register" => "Registers the supplied value in the active generation after validation.",
                "Unregister" => "Removes the supplied value from the active generation.",
                "Query" => "Evaluates whether the requested change can be applied to the current generation.",
                "Apply" => "Applies a validated change atomically at the caller-controlled commit point.",
                "Complete" => "Finalizes candidate activation and releases temporary transaction state.",
                "Rollback" or "RollbackStructure" or "RestorePreviousState" =>
                    "Restores the state captured before the current transaction began.",
                "Prepare" or "PrepareForActivation" =>
                    "Builds and validates candidate state without changing the active generation.",
                "RefreshDiagnostics" => "Recomputes diagnostics from the current candidate without publishing partial state.",
                "DisposeSnapshot" => "Releases the generation lease retained by an immutable registry snapshot.",
                "Undo" => "Restores the state that preceded this history operation.",
                "Redo" => "Reapplies the state represented by this history operation.",
                "Present" => "Presents this action through the current editor interaction surface.",
                "BindName" => "Binds a caller-visible label to the current inspection target.",
                "RequestClose" => "Queues a close request for processing at the next platform safety point.",
                "PollEvent" => "Attempts to dequeue the next backend-neutral platform event.",
                "RegisterExtension" => "Registers a platform extension for the application lifetime.",
                "ImportAsync" => "Imports source content into a validated runtime asset and artifact set.",
                "ExportAsync" => "Writes a validated asset representation to its writable source mount.",
                "BuildTools" => "Builds the native offline tools required by the selected configuration.",
                "Run" => "Executes the configured workflow and returns its process outcome.",
                "RunAsync" => "Runs the external tool asynchronously and captures its complete process outcome.",
                "BuildAsync" => "Builds and validates the requested artifact asynchronously before publishing it.",
                "IsIgnored" => "Determines whether source policy excludes the requested path from import.",
                "IsGeneratedPath" => "Determines whether a path belongs to engine-generated project output.",
                "DependsOnAsset" => "Records a dependency on another asset identity in the current import transaction.",
                "DependsOnArtifact" => "Records a dependency on a named artifact in the current import transaction.",
                "Reset" => "Restores this instance to its initial reusable state.",
                "Add" => "Adds the supplied value while preserving the collection's invariants.",
                "Remove" => "Removes the requested value while preserving the collection's invariants.",
                "Open" => "Opens the requested resource and establishes its active lifetime.",
                "Close" => "Closes the active resource and releases its operation-scoped state.",
                "Encode" or "Serialize" => "Encodes the supplied value into deterministic structured data.",
                "Decode" or "Deserialize" => "Decodes deterministic structured data into a validated value.",
                "Capture" => "Captures an immutable snapshot of the current observable state.",
                "Restore" => "Restores the supplied snapshot while preserving current invariants.",
                "Resolve" => "Resolves the requested stable identity to its current-generation value.",
                "Get" => "Resolves the requested identity to its current live value without extending that value's lifetime.",
                "Clear" => "Removes all retained entries and returns the instance to an empty reusable state.",
                "Flush" => "Commits buffered work to its destination before returning control to the caller.",
                "Cancel" => "Requests cancellation without publishing partially completed state.",
                "Commit" => "Publishes the prepared candidate atomically as the new active state.",
                "Activate" => "Makes the prepared value active at the owning subsystem's safety point.",
                "Deactivate" => "Removes the active value and releases its generation-scoped resources.",
                "Attach" => "Connects the supplied value to this owner's active lifetime.",
                "Detach" => "Disconnects the supplied value and releases state retained for its lifetime.",
                "Read" => "Reads and validates the requested value without transferring storage ownership.",
                "Write" => "Writes the supplied value through the owning subsystem's validated output boundary.",
                "Invoke" => "Invokes the configured callback within this instance's ownership boundary.",
                "Schedule" => "Queues the requested work for execution by the owning scheduler.",
                "Submit" => "Submits validated work to the active backend for ordered processing.",
                "Tick" => "Advances the owned state by one scheduler or frame boundary.",
                "Update" => "Recomputes owned state from the current validated inputs.",
                "Refresh" => "Rebuilds the caller-visible view from the current authoritative state.",
                "Initialize" => "Initializes owned resources and establishes the instance's active lifetime.",
                "Shutdown" => "Stops active work and releases resources in dependency order.",
                "Bind" => "Retains the supplied subscription until this owner is stopped or disposed.",
                "Publish" => "Publishes the supplied diagnostic to the configured observers.",
                "Receive" => "Receives one immutable entry and routes it through the active sink policy.",
                "Push" => "Pushes the supplied event onto the current execution context stack.",
                "PopIfCurrent" => "Removes the supplied event only when it is the current execution context.",
                "MarkHandledCurrent" => "Marks the current event handled without changing another event context.",
                "IsCurrent" => "Determines whether the supplied event owns the current execution context.",
                "IsCurrentHandled" => "Determines whether the current event context has been marked handled.",
                "Rebuild" => "Builds a complete candidate lookup from the supplied types before replacing current state.",
                "AddOrUpdate" => "Adds a new keyed value or atomically replaces the existing value for that key.",
                "AddKey" => "Adds one key to the indexed membership set.",
                "RemoveKey" => "Removes one key from the indexed membership set.",
                "IsKeyEmpty" => "Determines whether a key currently has no indexed values.",
                "Enumerate" => "Enumerates a stable view of the currently indexed keys.",
                "CombineDependencies" => "Combines the supplied job dependencies into one completion handle.",
                "ParallelFor" => "Schedules the indexed range in batches and returns its completion handle.",
                "CompleteAll" => "Waits until every supplied job handle has completed.",
                "EnqueueMainThread" => "Queues work for ordered execution on the owning main thread.",
                "DrainMainThreadQueue" => "Executes every queued main-thread callback in submission order.",
                "RequestCompilation" => "Creates a compilation ticket for the newest observable source generation.",
                "PrepareFrame" => "Prepares frame-owned resources before render graph recording begins.",
                "AddRenderPasses" => "Adds the renderer's frame passes and resource declarations to the render graph.",
                "Execute" when parent is TypeDeclarationSyntax type && type.Identifier.ValueText.Contains("Render", StringComparison.Ordinal) =>
                    "Executes the compiled render graph in dependency order for the supplied frame.",
                "BeginGraph" => "Begins recording commands for one validated compiled render graph.",
                "EndGraph" => "Finishes graph recording and submits its completed command stream.",
                "BeginPass" => "Begins recording commands for one compiled render pass.",
                "EndPass" => "Ends the active render pass and seals its recorded commands.",
                "BindGraphicsPipeline" => "Binds the graphics pipeline used by subsequent draw commands.",
                "BindComputePipeline" => "Binds the compute pipeline used by subsequent dispatch commands.",
                "BindTexture" => "Binds a texture resource to the requested shader binding.",
                "BindStorageTexture" => "Binds a writable texture resource to the requested shader binding.",
                "BindBuffer" => "Binds a buffer resource to the requested shader binding.",
                "BindVertexBuffer" => "Binds a vertex buffer and its first vertex for subsequent draws.",
                "BindIndexBuffer" => "Binds an index buffer and its first index for subsequent indexed draws.",
                "BindInstanceBuffer" => "Binds per-instance data for subsequent instanced draws.",
                "Dispatch" => "Dispatches compute work using the supplied thread-group dimensions.",
                "DispatchIndirect" => "Dispatches compute work using dimensions read from the supplied indirect buffer.",
                "BlitTexture" => "Copies the requested texture region into the destination texture resource.",
                "UploadBuffer" => "Uploads immutable frame data and returns the allocated transient buffer slice.",
                "BeginTextureReadback" => "Schedules asynchronous texture readback into caller-provided destination storage.",
                "CancelTextureReadback" => "Cancels a pending texture readback and releases its retained state.",
                "PrewarmTexture" => "Creates runtime GPU resources for the texture before its first render use.",
                "PrewarmMaterial" => "Creates runtime pipeline and binding resources for the material before first use.",
                "ResizeBackbuffer" => "Resizes the main presentation backbuffer to the requested pixel dimensions.",
                "ResizeViewport" => "Resizes an auxiliary viewport surface to its current platform dimensions.",
                "RenderMain" => "Records ImGui draw data for the main application viewport.",
                "RenderViewport" => "Records ImGui draw data for the supplied auxiliary viewport.",
                "PresentViewport" => "Presents the completed frame for the supplied auxiliary viewport.",
                "DestroyViewport" => "Destroys the auxiliary viewport and releases its rendering resources.",
                "SynchronizeMainOutput" => "Synchronizes the main render output with the current drawable dimensions.",
                "DestroyTexture" => "Destroys the texture after all in-flight references have retired.",
                "DestroyBuffer" => "Destroys the buffer after all in-flight references have retired.",
                "DestroyGraphicsPipeline" => "Destroys the graphics pipeline after all in-flight references have retired.",
                "DestroyComputePipeline" => "Destroys the compute pipeline after all in-flight references have retired.",
                "CanConvert" => "Determines whether a registered conversion connects the two stable shader value types.",
                "Compare" => "Compares two values according to the deterministic ordering used by this collection.",
                "ChangeProperty" => "Applies one serialized property edit and records its reversible history payload.",
                "CaptureContribution" => "Captures the contribution introduced by the supplied project setting value.",
                "Compose" => "Composes validated setting contributions into the final runtime setting.",
                "IsEmpty" => "Determines whether the contribution contains no changes from its baseline.",
                "Drop" => "Validates and applies the current editor drag-and-drop interaction atomically.",
                "Listen" => "Subscribes the supplied handler and returns ownership of the subscription lifetime.",
                "OnActivating" => "Validates and prepares a candidate snapshot before it can become active.",
                "OnActivationRolledBack" => "Restores state retained for the previous snapshot after candidate activation fails.",
                "OnActivationCompleted" => "Releases previous-generation state after the candidate becomes active.",
                "OnRuntimePayloadChanged" => "Rebuilds runtime-derived state after the serialized asset payload changes.",
                "OnCompleted" => "Commits the interaction after editing completes successfully.",
                "OnCancelled" => "Cancels the interaction without committing its pending value.",
                "OnPresentationLost" => "Cancels pending presentation state when its editor surface disappears.",
                "RemoveComponent" => "Removes the component from its scene owner and records a reversible serialized history change.",
                "RemoveSystem" => "Removes the system from its scene and records a reversible serialized history change.",
                "LoadIniSettings" => "Loads the current editor layout text into Dear ImGui without retaining the source string.",
                "RegisterFontStyle" => "Registers a named font style and its glyph ranges in the active ImGui font atlas.",
                "DispatchAwake" => "Dispatches the one-time Awake lifecycle callback to the scene object.",
                "DispatchStart" => "Dispatches the one-time Start lifecycle callback before regular updates begin.",
                "DispatchDestroy" => "Dispatches the terminal destruction callback before scene storage releases the object.",
                "DispatchEnable" => "Dispatches the enable callback immediately after the behavior becomes active.",
                "DispatchDisable" => "Dispatches the disable callback immediately before the behavior becomes inactive.",
                "IsValidKey" => "Determines whether the key belongs to a live slot in the current storage generation.",
                "Execute" when parent is TypeDeclarationSyntax actionType && actionType.Identifier.ValueText.Contains("Action", StringComparison.Ordinal) =>
                    "Applies the editor action to the supplied interaction context.",
                "Execute" => "Executes the prepared operation and publishes only a completed result.",
                "LoadUnmanagedDll" => "Loads a native dependency through the module's isolated resolution policy.",
                "Pack" => "Packs a storage slot and generation into one opaque runtime identifier.",
                "UnpackSlot" => "Extracts the storage slot encoded in an opaque runtime identifier.",
                "UnpackGeneration" => "Extracts the owner generation encoded in an opaque runtime identifier.",
                "Dot2" => "Calculates a two-component scalar dot product.",
                "Dot3" => "Calculates a three-component scalar dot product.",
                "Dot4" => "Calculates a four-component scalar dot product.",
                "Distance" => "Calculates the Euclidean distance between two points.",
                "Slerp" => "Interpolates along the shortest spherical path between two rotations.",
                "Inverse" => "Calculates the inverse rotation represented by the supplied quaternion.",
                "Conjugate" => "Returns the quaternion conjugate by negating its vector components.",
                "Union" => "Returns the smallest axis-aligned rectangle containing both supplied rectangles.",
                "FromMinMax" => "Creates a rectangle from inclusive minimum and maximum corner values.",
                "FromBytes" => "Creates a normalized color from byte channel values.",
                "ToBytes" => "Converts normalized color channels to clamped byte values.",
                "ToUInt32ARGB" => "Packs the color channels into an unsigned ARGB value.",
                "InsertSorted" => "Inserts a listener into the array while preserving deterministic priority order.",
                "RemoveByOrder" => "Removes the listener with the requested registration order from the immutable array.",
                _ when name.StartsWith("Try", StringComparison.Ordinal) =>
                    $"Attempts to {Humanize(name[3..])} without changing state when the operation cannot complete.",
                _ when name.StartsWith("Create", StringComparison.Ordinal) =>
                    $"Creates and validates a caller-owned {Humanize(name[6..])} value.",
                _ when name.StartsWith("Get", StringComparison.Ordinal) =>
                    $"Retrieves the current {Humanize(name[3..])} from authoritative state.",
                _ when name.StartsWith("Set", StringComparison.Ordinal) =>
                    $"Updates the {Humanize(name[3..])} state and applies the resulting invariants.",
                _ when name.StartsWith("Draw", StringComparison.Ordinal) =>
                    $"Renders the {Humanize(name[4..])} presentation for the current editor frame.",
                _ when name.StartsWith("Enter", StringComparison.Ordinal) =>
                    $"Begins the {Humanize(name[5..])} lifetime after validating its prerequisites.",
                _ when name.StartsWith("Exit", StringComparison.Ordinal) =>
                    $"Ends the {Humanize(name[4..])} lifetime and disposes its isolated state.",
                _ when name.StartsWith("Start", StringComparison.Ordinal) =>
                    $"Starts {Humanize(name[5..])} processing after validating the current state.",
                _ when name.StartsWith("Stop", StringComparison.Ordinal) =>
                    $"Stops {Humanize(name[4..])} processing and releases operation-scoped resources.",
                _ when name.StartsWith("Read", StringComparison.Ordinal) =>
                    $"Reads and validates the {Humanize(name[4..])} value from its authoritative source.",
                _ when name.StartsWith("Write", StringComparison.Ordinal) =>
                    $"Writes the {Humanize(name[5..])} value through the validated output boundary.",
                _ when name.StartsWith("Update", StringComparison.Ordinal) =>
                    $"Updates {Humanize(name[6..])} state from the current authoritative inputs.",
                _ when name.StartsWith("Refresh", StringComparison.Ordinal) =>
                    $"Refreshes the {Humanize(name[7..])} view from current authoritative state.",
                _ when name.StartsWith("Acquire", StringComparison.Ordinal) =>
                    $"Acquires caller-owned access to {Humanize(name[7..])} until the returned lifetime is released.",
                _ when name.StartsWith("Release", StringComparison.Ordinal) =>
                    $"Releases the caller-owned {Humanize(name[7..])} lifetime and its retained resources.",
                _ when name.StartsWith("Contains", StringComparison.Ordinal) =>
                    $"Determines whether current state contains the requested {Humanize(name[8..])} value.",
                _ when name.StartsWith("Find", StringComparison.Ordinal) =>
                    $"Searches current state for the requested {Humanize(name[4..])} value.",
                _ when name.StartsWith("Convert", StringComparison.Ordinal) =>
                    $"Converts {Humanize(name[7..])} into the representation required by the caller.",
                _ when name.StartsWith("From", StringComparison.Ordinal) =>
                    $"Creates the target representation from the supplied {Humanize(name[4..])} value.",
                _ when name.StartsWith("To", StringComparison.Ordinal) =>
                    $"Converts this value to its {Humanize(name[2..])} representation.",
                _ when name.StartsWith("For", StringComparison.Ordinal) =>
                    $"Creates a deferred resource record for the supplied {Humanize(name[3..])} handle.",
                _ when name.StartsWith("Bind", StringComparison.Ordinal) =>
                    $"Binds {Humanize(name[4..])} state for subsequent commands in the current encoding scope.",
                _ when name.StartsWith("Destroy", StringComparison.Ordinal) =>
                    $"Destroys the {Humanize(name[7..])} after its in-flight references retire.",
                _ when name.StartsWith("Render", StringComparison.Ordinal) =>
                    $"Records {Humanize(name[6..])} rendering for the current frame.",
                _ when name.StartsWith("Resize", StringComparison.Ordinal) =>
                    $"Resizes the {Humanize(name[6..])} resources to match current presentation dimensions.",
                _ when name.StartsWith("Begin", StringComparison.Ordinal) =>
                    $"Begins the {Humanize(name[5..])} operation and establishes its scoped lifetime.",
                _ when name.StartsWith("End", StringComparison.Ordinal) =>
                    $"Ends the {Humanize(name[3..])} operation and seals its completed state.",
                _ when name.StartsWith("On", StringComparison.Ordinal) =>
                    $"Handles the {Humanize(name[2..])} lifecycle notification for the current generation.",
                _ when name.StartsWith("Copy", StringComparison.Ordinal) =>
                    $"Copies {Humanize(name[4..])} without transferring ownership of the source state.",
                _ when name.StartsWith("Visit", StringComparison.Ordinal) =>
                    $"Visits {Humanize(name[5..])} in deterministic order using the supplied visitor.",
                _ when name.StartsWith("Process", StringComparison.Ordinal) =>
                    $"Processes {Humanize(name[7..])} and commits only a fully validated result.",
                _ => $"Runs the {Humanize(name)} operation and commits only state accepted by this type's invariants."
            };

        private static string DescribeOperator(string token)
            => token switch
            {
                "+" => "Adds the supplied values component by component.",
                "-" => "Subtracts or negates the supplied value component by component.",
                "*" => "Multiplies the supplied values according to their algebraic contract.",
                "/" => "Divides the supplied value by the scalar divisor component by component.",
                "==" => "Determines whether the supplied values are equal under the type's equality tolerance.",
                "!=" => "Determines whether the supplied values differ under the type's equality tolerance.",
                _ => $"Applies the <c>{token}</c> operator to the supplied values."
            };

        private static string DescribeProperty(string name, TypeSyntax type)
        {
            if (name == "normalized")
                return "Gets a unit-length copy, or the zero value when normalization is undefined.";
            if (name.StartsWith("is", StringComparison.Ordinal) && type.ToString() == "bool")
                return $"Gets whether this value is {Humanize(name[2..])}.";
            if (name.StartsWith("has", StringComparison.Ordinal) && type.ToString() == "bool")
                return $"Gets whether this value has {Humanize(name[3..])}.";
            if (name.StartsWith("can", StringComparison.Ordinal) && type.ToString() == "bool")
                return $"Gets whether this value can {Humanize(name[3..])}.";
            return name switch
            {
                "id" or "identity" => "Gets the stable identity used to reference this value across subsystem boundaries.",
                "name" => "Gets the human-readable name used for presentation and diagnostics.",
                "state" => "Gets the current lifecycle state observed by callers.",
                "status" => "Gets the current human-readable operation status.",
                "description" => "Gets the user-facing explanation of this feature or setting.",
                "section" => "Gets the presentation section that groups this setting.",
                "defaultValue" => "Gets a new value initialized to this setting's canonical default state.",
                "initialSize" => "Gets the preferred initial window size in logical editor units.",
                "outputPlatform" => "Gets the native platform identifier produced by this builder.",
                "buildType" => "Gets the native build configuration selected for the current invocation.",
                "debugMakeTarget" => "Gets the native make target used for debug output.",
                "releaseMakeTarget" => "Gets the native make target used for optimized output.",
                "targetType" or "definitionType" or "sourceType" =>
                    "Gets the concrete type handled by this extension implementation.",
                "icon" => "Gets the icon glyph used to represent this item in the editor.",
                "stableAssetTypeId" => "Gets the stable type identity stored with serialized asset data.",
                "propertyData" => "Gets the neutral serialized property payload owned by this record.",
                "dependencies" => "Gets the stable dependency identities required by this value.",
                "supportedExtensions" => "Gets the normalized source extensions accepted by this importer.",
                "importerId" => "Gets the stable importer identity used in artifact fingerprints.",
                "estimatedMemorySize" => "Gets the estimated resident-memory cost in bytes.",
                "estimatedDiskSize" => "Gets the estimated spill-file cost in bytes.",
                "libraryName" => "Gets the platform-specific native library name loaded by this binding.",
                "isNull" => "Gets whether this native wrapper contains no handle.",
                "null" or "Null" => "Gets an empty native pointer wrapper that references no allocation.",
                "context" => "Gets the candidate activation context shared with participating registries.",
                "SupportedDiagnostics" => "Gets the complete compiler diagnostic set enforced by this analyzer.",
                "count" => "Gets the number of values in the current immutable view.",
                "generation" => "Gets the generation identity that owns this value.",
                "revision" => "Gets the monotonic change identity for the current state.",
                "lastFailure" => "Gets the most recent transition failure, or null when no failure is active.",
                "activeSessionId" => "Gets the isolated log session that owns the current Play Mode request.",
                "targetAssetType" => "Gets the runtime asset type accepted by this importer implementation.",
                "result" => "Gets the completed compilation result, or null while work is still pending.",
                "lastCompilation" => "Gets the most recently activated script compilation result.",
                "currentTicket" => "Gets the ticket for the newest requested compilation, or null when idle.",
                "minimumSize" => "Gets the smallest editor window size that keeps every setting control usable.",
                "document" => "Gets the graph document currently owned by the editor module.",
                "settingId" => "Gets the stable project-setting identity used for discovery and persistence.",
                "phase" => "Gets the render phase that owns this pass declaration.",
                "kind" => "Gets the operation kind that determines how this value is interpreted.",
                "execute" => "Gets the callback that records commands for this render pass.",
                "before" => "Gets the render phases that must execute after this pass.",
                "after" => "Gets the render phases that must execute before this pass.",
                "resources" => "Gets the complete resource access declarations used for graph dependency analysis.",
                "attachments" => "Gets the color and depth attachments written by this render pass.",
                "surface" => "Gets the presentation surface targeted by this render pass.",
                "presentationClearColor" => "Gets the color used when the presentation surface is cleared.",
                "viewTransform" => "Gets the optional view and projection transform applied by this pass.",
                "recordingMode" => "Gets whether the pass records graphics, compute, or transfer commands.",
                "capabilities" => "Gets the immutable feature and limit set reported by the active graphics backend.",
                "target" => "Gets the platform viewport whose render resources are tracked by this state.",
                "packet" => "Gets the most recently prepared immutable draw packet, or null before preparation.",
                "definitionData" => "Gets the serialized shader definition bytes stored in the artifact.",
                "passes" => "Gets the ordered compiled shader passes stored in the artifact.",
                "varyingSource" => "Gets optional varying declarations shared by raster stages.",
                "bindingIds" => "Gets the stable shader binding identities used by the compiled stage.",
                "stages" => "Gets the compiled shader stages that form this pass.",
                "stage" => "Gets the shader stage represented by this compiled payload.",
                "frameBuffer" => "Gets the BGFX framebuffer owned by this presentation surface.",
                "nativeHandles" => "Gets the platform-native window and display handles used to create the surface.",
                "descriptor" => "Gets the backend-neutral descriptor used to validate and recreate this resource.",
                "vertexLayout" => "Gets the optional vertex layout required by this resource or pipeline.",
                "indexFormat" => "Gets the element width used by this index buffer.",
                "nativeIndex" => "Gets the BGFX dynamic-buffer index used by deferred destruction.",
                "uniform" => "Gets the BGFX uniform handle backing this shader binding.",
                "program" => "Gets the linked BGFX shader program owned by this pipeline resource.",
                "bindings" => "Gets the immutable lookup of stable binding IDs to BGFX uniform resources.",
                "vertexLayoutHandle" => "Gets the BGFX vertex-layout handle owned by this pipeline resource.",
                "rasterState" => "Gets the optional rasterization state encoded by this pipeline.",
                "primaryPresentationSize" => "Gets the current drawable pixel size of the main presentation surface.",
                "frameCounters" => "Gets the submitted and completed frame counters used for deferred retirement.",
                "domain" => "Gets the assembly domain that produced this script log call.",
                "scope" => "Gets the assembly scope captured for this script log call.",
                "min" => "Gets the minimum corner of this axis-aligned rectangle.",
                "max" => "Gets the maximum corner of this axis-aligned rectangle.",
                "size" => "Gets the width and height derived from the rectangle bounds.",
                "center" => "Gets the midpoint derived from the rectangle bounds.",
                "buckets" => "Gets the immutable listener buckets captured for one dispatch operation.",
                "owner" => "Gets the object that owns the coroutine lifetime.",
                "routine" => "Gets the root enumerator advanced by this coroutine.",
                "stack" => "Gets the nested enumerator stack retained by this coroutine.",
                "waiter" => "Gets the current continuation predicate, or null when the coroutine can advance.",
                "sourcePersistentId" => "Gets the persistent identity of the script source represented by this manifest.",
                "declarations" => "Gets the stable attachable-type declarations discovered in the script source.",
                "keyType" => "Gets the key type accepted by this index implementation.",
                "flags" => "Gets the index capabilities supported by this key declaration.",
                "supportedDiagnostics" => "Gets the compiler diagnostics enforced by the logical scripting API analyzer.",
                "deploymentScope" => "Gets whether imported output is deployed to runtime, editor, or both domains.",
                _ when name.EndsWith("Path", StringComparison.Ordinal) =>
                    $"Gets the normalized {Humanize(name)} used by the current operation.",
                _ when name.EndsWith("Directory", StringComparison.Ordinal) || name.EndsWith("Root", StringComparison.Ordinal) =>
                    $"Gets the normalized {Humanize(name)} owned by this instance.",
                _ when type.ToString() == "bool" => $"Gets whether {Humanize(name)} is active for the current instance.",
                _ when type.ToString() == "string" => $"Gets the {Humanize(name)} text used by the current instance.",
                _ when type.ToString() is "int" or "uint" or "long" or "ulong" or "float" or "double" =>
                    $"Gets the {Humanize(name)} scalar measured or assigned by the current instance.",
                _ => $"Gets the {Humanize(name)} value owned by the current instance."
            };
        }

        private static string DescribeField(string name)
            => name switch
            {
                "x" => "The horizontal or first component.",
                "y" => "The vertical or second component.",
                "z" => "The depth or third component.",
                "w" => "The homogeneous or fourth component.",
                "r" => "The red color component.",
                "g" => "The green color component.",
                "b" => "The blue color component.",
                "a" => "The alpha color component.",
                "ZERO" => "A value whose components are all zero.",
                "ONE" => "A value whose components are all one.",
                "null" => "An empty native pointer wrapper that references no allocation.",
                "context" => "The operation context retained only for the lifetime of this nested scope.",
                "supportedDiagnostics" => "The immutable compiler diagnostics enforced by this analyzer.",
                _ when name.StartsWith("UNIT_", StringComparison.Ordinal) =>
                    $"A unit value aligned with the {name[5..].ToLowerInvariant()} axis.",
                _ => $"The {Humanize(name)} value used as part of this type's public representation."
            };

        private static string DescribeEnumMember(string name)
        {
            if (name == "Unknown")
                return "No recognized physical key.";
            if (name.Length == 1 && char.IsLetter(name[0]))
                return $"The {name} letter key.";
            if (name.Length == 2 && name[0] == 'D' && char.IsDigit(name[1]))
                return $"The {name[1]} key on the primary keyboard row.";
            if (name.StartsWith("NumPad", StringComparison.Ordinal))
                return $"The {name[6..]} key on the numeric keypad.";
            if (name.Length is 2 or 3 && name[0] == 'F' && int.TryParse(name[1..], out _))
                return $"The {name} function key.";
            return $"The {Humanize(name)} key.";
        }

        private static string DescribeParameter(ParameterSyntax parameter, string operationName)
        {
            string name = parameter.Identifier.ValueText;
            return name switch
            {
                "x" => "The horizontal or first component.",
                "y" => "The vertical or second component.",
                "z" => "The depth or third component.",
                "w" => "The homogeneous or fourth component.",
                "a" => "The first operand or interpolation endpoint.",
                "b" => "The second operand or interpolation endpoint.",
                "v" or "value" or "vector" => "The concrete value read or transformed by this operation.",
                "from" => "The starting value used by the operation.",
                "to" => "The destination value used by the operation.",
                "t" => "The interpolation factor, where zero selects the first endpoint and one selects the second.",
                "scalar" => "The scalar applied to every component.",
                "epsilon" => "The positive tolerance below which input is treated as degenerate.",
                "rotation" => "The rotation applied to the supplied value.",
                "m" or "matrix" => "The transformation matrix applied to the supplied value.",
                "n" or "normal" => "The surface normal used by the operation.",
                "obj" => "The object compared with this value.",
                "other" => "The strongly typed value compared with this value.",
                "cancellationToken" => "The token that cancels the operation before it commits.",
                "args" or "arguments" => "The command-line arguments that configure this invocation.",
                "context" => "The operation scope that provides state, services, and ownership boundaries.",
                "reader" => "The reader positioned at the structured value to decode.",
                "writer" => "The writer that receives the deterministic structured representation.",
                "request" => "The validated immutable request that defines this operation.",
                "result" => "The result produced or completed by the preceding operation.",
                "options" or "config" or "configuration" or "profile" or "settings" =>
                    "The validated configuration that controls this operation.",
                "types" => "The active type catalog generation used for extension resolution.",
                "snapshot" => "The immutable state snapshot consumed by this operation.",
                "state" => "The lifecycle or domain state applied by this operation.",
                "change" => "The neutral change payload to query or apply.",
                "direction" => "The history direction that determines which state is applied.",
                "data" or "bytes" => "The complete immutable byte payload consumed by this operation.",
                "path" or "sourcePath" or "destinationPath" => "The normalized file-system path used by this operation.",
                "root" or "rootPath" or "directory" or "outputDirectory" =>
                    "The normalized directory that owns this operation's files.",
                "source" => "The source value or location read by this operation.",
                "destination" => "The destination that receives the completed result.",
                "index" => "The zero-based position of the requested value.",
                "count" => "The non-negative number of values affected by this operation.",
                "width" => "The width in logical units or pixels required by this operation.",
                "height" => "The height in logical units or pixels required by this operation.",
                "frameIndex" => "The monotonic frame identity associated with this operation.",
                "capabilities" => "The immutable graphics capabilities used to validate the operation.",
                "colorSpace" => "The color transfer convention preserved in the compiled texture artifact.",
                "optimize" => "Whether the compiler should optimize the generated runtime artifact.",
                "debugInformation" => "Whether the compiler should retain target debug information.",
                "setting" => "The mutable editor setting value currently being presented.",
                "reportCleanupFailure" => "The callback that receives cleanup failures without interrupting remaining cleanup.",
                "scripting" => "The scripting workflow whose compilation state is presented by this component.",
                "zoom" => "The editor zoom service modified by this action.",
                "selectedTarget" => "The current inspection target used to render the header.",
                "assets" => "The active authoring Asset Pipeline used by this feature.",
                "gameObject" => "The scene object captured by this structural snapshot.",
                "components" => "The ordered component state captured with the owning scene object.",
                "windowId" => "The backend-neutral identity of the window that produced this event.",
                "offsetX" => "The horizontal scroll delta reported by the platform.",
                "offsetY" => "The vertical scroll delta reported by the platform.",
                "button" => "The backend-neutral mouse button associated with this event.",
                "key" => "The backend-neutral physical key associated with this event.",
                "modifiers" => "The modifier-key state captured with this keyboard event.",
                "repeat" => "Whether the platform generated this key press through key repeat.",
                "frames" => "The number of frame boundaries that must pass before resuming.",
                "seconds" => "The non-negative duration in seconds that must pass before resuming.",
                "predicate" => "The condition evaluated to decide whether coroutine execution can resume.",
                "task" => "The asynchronous operation whose completion resumes coroutine execution.",
                "slot" => "The dense storage slot encoded in this runtime handle.",
                "generation" => "The owner generation used to reject stale handles or snapshots.",
                "handle" => "The opaque handle validated by this operation.",
                "item" => "The stored item associated with the validated handle.",
                "output" => "The import output writer that receives runtime data and dependency declarations.",
                "asset" => "The validated asset instance exported by this operation.",
                "catalog" => "The candidate asset catalog prepared for activation.",
                "persistentId" => "The stable persistent identity used for lookup.",
                "info" => "The resolved immutable metadata returned to the caller.",
                "artifact" => "The resolved immutable artifact payload returned to the caller.",
                "outputName" => "The stable artifact output name used for lookup.",
                "relativePath" => "The normalized path relative to its owning source mount.",
                "isDirectory" => "Whether the source entry represents a directory.",
                "older" => "The earlier history payload considered for coalescing.",
                "newer" => "The later history payload considered for coalescing.",
                "merged" => "Receives the neutral coalesced payload when merging succeeds.",
                "disposing" => "Whether the owner is permanently disposing rather than clearing reusable state.",
                "exception" => "The failure captured for diagnostics without changing active state.",
                "callback" or "action" or "factory" => "The caller-provided delegate invoked within this operation's lifetime.",
                "target" => "The existing target that receives the validated result.",
                "owner" => "The object that owns the resulting lifetime and state.",
                "id" => "The stable identity used to locate the requested value.",
                "name" => "The human-readable name used for presentation and diagnostics.",
                _ => operationName == "operation"
                    ? $"The {Humanize(parameter.Type?.ToString() ?? name)} value used to initialize this instance."
                    : DescribeUnclassifiedParameter(parameter, operationName)
            };
        }

        private static string DescribeUnclassifiedParameter(ParameterSyntax parameter, string operationName)
        {
            string name = parameter.Identifier.ValueText;
            string type = parameter.Type?.ToString() ?? string.Empty;
            if (type is "bool" or "bool?")
                return $"Whether {Humanize(name)} behavior is enabled while {Humanize(operationName)} executes.";
            if (type is "string" or "string?")
                return $"The {Humanize(name)} text validated by the {Humanize(operationName)} operation.";
            if (type.Contains("Action", StringComparison.Ordinal) || type.Contains("Func", StringComparison.Ordinal))
                return $"The callback invoked by {Humanize(operationName)} within the operation's owned lifetime.";
            return $"The {Humanize(name)} consumed by {Humanize(operationName)}; ownership remains with the caller unless explicitly stated otherwise.";
        }

        private static string DescribeEvent(string name)
        {
            string subject = name.EndsWith("Changed", StringComparison.Ordinal) && name.Length > "Changed".Length
                ? Humanize(name[..^"Changed".Length])
                : Humanize(name);
            return $"Occurs after the observable {subject} state changes.";
        }

        private static string DescribeReturn(string operationName, TypeSyntax returnType)
        {
            string type = returnType.ToString();
            if (type == "bool")
                return operationName.StartsWith("Try", StringComparison.Ordinal)
                    ? "<see langword=\"true\"/> when the requested result was produced; otherwise, <see langword=\"false\"/>."
                    : "<see langword=\"true\"/> when the documented condition is satisfied; otherwise, <see langword=\"false\"/>.";
            if (type == "string")
                return "The validated text representation owned by the caller.";
            if (type is "float" or "double" or "int" or "long")
                return "The scalar result calculated from the supplied inputs.";
            if (type.Contains("Task", StringComparison.Ordinal))
                return "An asynchronous operation that completes after all requested work has finished.";
            if (type.Contains("IReadOnly", StringComparison.Ordinal) || type.EndsWith("[]", StringComparison.Ordinal))
                return "An immutable snapshot of the values selected by the operation.";
            return $"The validated {Humanize(type)} that represents the completed operation."
                .Replace("<", "", StringComparison.Ordinal)
                .Replace(">", "", StringComparison.Ordinal);
        }

        private static string EscapeType(TypeSyntax type)
            => type.ToString().Replace("<", "{", StringComparison.Ordinal).Replace(">", "}", StringComparison.Ordinal);

        private static string Humanize(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
                return "value";
            var builder = new StringBuilder(value.Length + 8);
            for (int index = 0; index < value.Length; index++)
            {
                char character = value[index];
                if (character == '_')
                {
                    builder.Append(' ');
                    continue;
                }
                if (index > 0 && char.IsUpper(character) && char.IsLower(value[index - 1]))
                    builder.Append(' ');
                builder.Append(char.ToLowerInvariant(character));
            }
            return builder.ToString();
        }
    }
}
