<Project>
  <Import Project="../Directory.Build.props" />
  <PropertyGroup Condition="'$(InnoAssemblyDomain)' == ''">
    <InnoAssemblyDomain>InnoInternal</InnoAssemblyDomain>
  </PropertyGroup>
  <PropertyGroup Condition="'$(InnoAssemblyScope)' == ''">
    <InnoAssemblyScope>Runtime</InnoAssemblyScope>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS8981</NoWarn>
    <WarningsAsErrors>$(WarningsAsErrors);CS1572;CS1573;CS1591</WarningsAsErrors>
    <BindGenRoot Condition="'$(BindGenRoot)' == ''">$(MSBuildThisFileDirectory)..\..\BindGen-CS</BindGenRoot>
    <BGCSRuntimeProject Condition="'$(BGCSRuntimeProject)' == '' and Exists('$(BindGenRoot)\src\BGCS.Runtime\BGCS.Runtime.csproj')">$(BindGenRoot)\src\BGCS.Runtime\BGCS.Runtime.csproj</BGCSRuntimeProject>
    <BindGenProfile Condition="'$(InnoNativeTarget)' != '' and Exists('$(MSBuildProjectDirectory)/Bindings/bindgen.$(InnoNativeTarget).json')">$(InnoNativeTarget)</BindGenProfile>
    <BindGenConfig Condition="'$(BindGenProfile)' != ''">$(MSBuildProjectDirectory)/Bindings/bindgen.$(BindGenProfile).json</BindGenConfig>
    <BindGenTargetOutputRoot Condition="'$(BindGenProfile)' != ''">$(MSBuildProjectDirectory)/obj/$(BindGenProfile)</BindGenTargetOutputRoot>
    <DefineConstants Condition="'$(BindGenProfile)' == 'browser-wasm'">$(DefineConstants);INNO_STATIC_NATIVE</DefineConstants>
  </PropertyGroup>
</Project>
