<Project>
  <PropertyGroup Condition="'$(InnoAssemblyDomain)' == ''">
    <InnoAssemblyDomain>InnoInternal</InnoAssemblyDomain>
  </PropertyGroup>
  <PropertyGroup Condition="'$(InnoAssemblyScope)' == ''">
    <InnoAssemblyScope>Runtime</InnoAssemblyScope>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1570;CS1572;CS1573;CS1574;CS1591;CS8981</NoWarn>
    <BindGenRoot Condition="'$(BindGenRoot)' == ''">$(MSBuildThisFileDirectory)..\..\BindGen-CS</BindGenRoot>
    <BGCSRuntimeProject Condition="'$(BGCSRuntimeProject)' == '' and Exists('$(BindGenRoot)\src\BGCS.Runtime\BGCS.Runtime.csproj')">$(BindGenRoot)\src\BGCS.Runtime\BGCS.Runtime.csproj</BGCSRuntimeProject>
  </PropertyGroup>
</Project>
