using Inno.Scripting.Api;
using Inno.Editor.Interactions;

[assembly: ScriptingApiNamespace(
    "InnoEditor.Interactions",
    "Inno.Editor.Interactions",
    ScriptingApiScope.Editor)]

[assembly: ScriptingApiExport(typeof(EditorInteractions), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorInteraction), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorSelectionState), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(IEditorSelectionCoordinator), ScriptingApiScope.Editor)]

[assembly: ScriptingApiExport(typeof(EditorAction), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorAction<>), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorAction<,>), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorArgumentAction<>), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorPresentationAction<,>), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorActionAttribute), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorActionContext), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorActionContext<>), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorActionContext<,>), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorActionArgumentContext<>), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorActionState), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorShortcutAttribute), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorValidationResult), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(HotKeyGesture), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(IEditorHistory), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorHistoryAvailability), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorHistoryChange), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorHistoryContext), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorHistoryDirection), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorHistoryHandler), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorHistoryHandlerAttribute), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorHistoryPayload), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorHistoryResult), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorHistoryTransaction), ScriptingApiScope.Editor)]

[assembly: ScriptingApiExport(typeof(IEditorDocumentService), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorDocumentProvider), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorDocumentContext), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorDocumentCloseMode), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorViewportPointerPhase), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorViewportCursor), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorViewportShortcut), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorViewportPointerEvent), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(IEditorViewportCoordinateConverter), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorViewportTool), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorViewportToolContext), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorViewportToolSession), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorPlanarNavigation), ScriptingApiScope.Editor)]

[assembly: ScriptingApiExport(typeof(EditorMenuAttribute), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorMenuBuilder), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorMenuContext), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorMenuItem), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorMenuModel), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorMenuSource), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorMenuSourceAttribute), ScriptingApiScope.Editor)]

[assembly: ScriptingApiExport(typeof(EditorToolbarIcon), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorToolbarItem), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorToolbarItemAttribute), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorToolbarModel), ScriptingApiScope.Editor)]

[assembly: ScriptingApiExport(typeof(EditorDragData), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorDragContext), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorDrop), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorDrop<,>), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorDropAttribute), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorDropContext), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorDropContext<,>), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorDropPlacement), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorDropResult), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorDropStatus), ScriptingApiScope.Editor)]
[assembly: ScriptingApiExport(typeof(EditorDropVisual), ScriptingApiScope.Editor)]
