<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1572;CS1573;CS1591</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Inno.Core.Execution/Inno.Core.Execution.csproj" />
    <ProjectReference Include="../Inno.Core.Events/Inno.Core.Events.csproj" />
    <ProjectReference Include="../../extensibility/Inno.Extensibility.Catalogs/Inno.Extensibility.Catalogs.csproj" />
  </ItemGroup>
</Project>
