<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-browser</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Inno.Adapter.Storage/Inno.Adapter.Storage.csproj" />
    <ProjectReference Include="../../../services/storage/Inno.Storage/Inno.Storage.csproj" />
  </ItemGroup>
</Project>
