<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1572;CS1573;CS1591</WarningsAsErrors>
    <DefaultItemExcludes>$(DefaultItemExcludes);**/bin/**;**/obj/**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../foundation/core/Inno.Core.IO/Inno.Core.IO.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../../deployment/Inno.Content/Inno.Content.csproj" />
    <ProjectReference
      Include="../../../foundation/scripting/Inno.Scripting.Api/Inno.Scripting.Api.csproj"
      PrivateAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../foundation/core/Inno.Core.Serialization/Inno.Core.Serialization.csproj" />
    <ProjectReference Include="../../../foundation/core/Inno.Core.Identity/Inno.Core.Identity.csproj" />
    <ProjectReference Include="../../../foundation/extensibility/Inno.Extensibility.Types/Inno.Extensibility.Types.csproj" />
    <ProjectReference Include="../../references/Inno.References/Inno.References.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="../../../foundation/core/Inno.Core.Execution/Inno.Core.Execution.csproj"
      PrivateAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../runtime/contracts/Inno.Runtime.Contracts/Inno.Runtime.Contracts.csproj" />
    <ProjectReference Include="../../../foundation/extensibility/Inno.Extensibility.Catalogs/Inno.Extensibility.Catalogs.csproj" />
  </ItemGroup>
</Project>
