<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1572;CS1573;CS1591</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../extensibility/Inno.Extensibility.Reload/Inno.Extensibility.Reload.csproj" />
    <ProjectReference
      Include="../../extensibility/Inno.Extensibility.Types/Inno.Extensibility.Types.csproj"
      PrivateAssets="compile" />
    <ProjectReference Include="../../scripting/Inno.Scripting.Api/Inno.Scripting.Api.csproj" PrivateAssets="compile" />
    <ProjectReference Include="../Inno.Core.Collections/Inno.Core.Collections.csproj" PrivateAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Inno.Core.IO/Inno.Core.IO.csproj" />
    <ProjectReference Include="../Inno.Core.Serialization/Inno.Core.Serialization.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Inno.Core.Execution/Inno.Core.Execution.csproj" PrivateAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../extensibility/Inno.Extensibility.Catalogs/Inno.Extensibility.Catalogs.csproj" />
  </ItemGroup>
</Project>
