using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Inno.Core.Serialization.Generators;

internal sealed class SerializationMetadataScope
{
    internal const string C_CATALOG = "__InnoGeneratedSerializationCatalog";
    private readonly List<SerializationMetadataScope> m_children = [];
    private int m_index;

    internal SerializationMetadataScope(INamedTypeSymbol? owner) => this.owner = owner;

    internal INamedTypeSymbol? owner { get; }
    internal StringBuilder registrations { get; } = new();
    internal StringBuilder creators { get; } = new();
    internal StringBuilder lookup { get; } = new();
    internal StringBuilder accessors { get; } = new();
    internal ref int index => ref m_index;

    internal void Add(SerializationMetadataScope child) => m_children.Add(child);

    internal string Emit(string assemblyName)
    {
        var code = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        var owners = new Stack<INamedTypeSymbol>();
        for (INamedTypeSymbol? current = owner; current is not null; current = current.ContainingType)
            owners.Push(current);
        string namespaceName = owner is null ? assemblyName + ".Generated"
            : owner.ContainingNamespace.IsGlobalNamespace ? "" : owner.ContainingNamespace.ToDisplayString();
        if (namespaceName.Length > 0)
            code.Append("namespace ").Append(namespaceName).Append(";\n");
        foreach (INamedTypeSymbol declaration in owners)
            code.Append(Declaration(declaration)).Append("\n{\n");
        bool root = owner is null;
        if (root)
            code.Append("/// <summary>\n/// Supplies closed serialization access and construction for this assembly.\n/// </summary>\n");
        code.Append(root ? "public" : "internal").Append(" static class ")
            .Append(root ? "RuntimeSerializationMetadataCatalog" : C_CATALOG).Append("\n{\n")
            .Append("    /// <summary>\n    /// Contributes generated metadata without retaining the composition callback.\n    /// </summary>\n")
            .Append("    /// <param name=\"register\">\n    /// The composition-owned registration callback.\n    /// </param>\n")
            .Append("    /// <exception cref=\"global::System.ArgumentNullException\">\n    /// The callback is null.\n    /// </exception>\n")
            .Append("    ").Append(root ? "public" : "internal")
            .Append(" static void Register(global::System.Action<global::Inno.Core.Serialization.SerializationTypeMetadata> register)\n    {\n")
            .Append("        global::System.ArgumentNullException.ThrowIfNull(register);\n")
            .Append(registrations);
        foreach (SerializationMetadataScope child in m_children)
            code.Append("        ").Append(ChildName(child, root)).Append(".Register(register);\n");
        code.Append("    }\n")
            .Append("    /// <summary>\n    /// Creates metadata through its declaration's generated accessors.\n    /// </summary>\n")
            .Append("    /// <param name=\"type\">\n    /// The exact closed declaration.\n    /// </param>\n")
            .Append("    /// <returns>\n    /// Complete access metadata for an owned declaration.\n    /// </returns>\n")
            .Append("    /// <exception cref=\"global::System.ArgumentNullException\">\n    /// The declaration is null.\n    /// </exception>\n")
            .Append("    ").Append(root ? "public" : "internal")
            .Append(" static global::Inno.Core.Serialization.SerializationTypeMetadata")
            .Append(root ? " GetMetadata" : "? FindMetadata").Append("(global::System.Type type)\n    {\n")
            .Append("        global::System.ArgumentNullException.ThrowIfNull(type);\n")
            .Append(lookup);
        if (m_children.Count > 0)
        {
            code.Append("        global::Inno.Core.Serialization.SerializationTypeMetadata? metadata;\n");
            foreach (SerializationMetadataScope child in m_children)
                code.Append("        metadata = ").Append(ChildName(child, root)).Append(".FindMetadata(type);\n")
                    .Append("        if (metadata is not null) return metadata;\n");
        }
        code.Append(root
            ? "        throw new global::System.ArgumentException(\"The serialization declaration is not registered.\", nameof(type));\n"
            : "        return null;\n")
            .Append("    }\n").Append(creators).Append(accessors)
            .Append("    private static T[] BuildArray<T>(global::System.Collections.Generic.IReadOnlyList<object?> values)\n    {\n")
            .Append("        var result = new T[values.Count];\n        for (int index = 0; index < result.Length; index++)\n")
            .Append("            result[index] = (T)values[index]!;\n        return result;\n    }\n}\n");
        foreach (INamedTypeSymbol _ in owners)
            code.Append("}\n");
        return code.ToString();
    }

    internal static bool CanExtend(INamedTypeSymbol owner)
        => owner.TypeParameters.Length == 0 && !owner.IsFileLocal && owner.DeclaringSyntaxReferences.Length > 0
            && owner.DeclaringSyntaxReferences.All(static reference => reference.GetSyntax() is TypeDeclarationSyntax syntax
                && syntax.Modifiers.Any(SyntaxKind.PartialKeyword));

    private static string ChildName(
        SerializationMetadataScope child,
        bool root
    ) => (root ? child.owner!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) : "@" + child.owner!.Name)
        + "." + C_CATALOG;

    private static string Declaration(INamedTypeSymbol type)
    {
        string visibility = type.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "internal"
        };
        string modifiers = type.IsStatic ? " static" : type.IsReadOnly ? " readonly" : "";
        string kind = type.IsRecord ? type.IsValueType ? "record struct" : "record class"
            : type.TypeKind == TypeKind.Struct ? "struct" : "class";
        return visibility + modifiers + " partial " + kind + " @" + type.Name;
    }
}
