<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1572;CS1573;CS1591</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Inno.Adapter.Text\Inno.Adapter.Text.csproj" />
    <ProjectReference Include="..\..\..\services\text\Inno.Text\Inno.Text.csproj" />
    <ProjectReference Include="..\..\..\..\native\Inno.Native.Text\Inno.Native.Text.csproj" PrivateAssets="compile" />
  </ItemGroup>
</Project>
