<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <BindGenGeneratedBindings>true</BindGenGeneratedBindings>
    <BindGenExtensionProject>$(MSBuildProjectDirectory)/Bindings/Extension/Inno.Native.ImGui.BindingExtension.csproj</BindGenExtensionProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Inno.Native.LibraryLoading\Inno.Native.LibraryLoading.csproj" PrivateAssets="compile" />
    <ProjectReference Include="$(BGCSRuntimeProject)" Condition="'$(BGCSRuntimeProject)' != ''" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BGCS.Runtime" Version="1.0.1" Condition="'$(BGCSRuntimeProject)' == ''" />
  </ItemGroup>
</Project>
