<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <BindGenGeneratedBindings>true</BindGenGeneratedBindings>
  </PropertyGroup>

  <Import Project="Bindings/bindings.props" />

  <ItemGroup>
    <ProjectReference Include="../../../Interop/native/Inno.Native.LibraryLoading/Inno.Native.LibraryLoading.csproj" PrivateAssets="compile" />
    <ProjectReference Include="$(BGCSRuntimeProject)" />
  </ItemGroup>
</Project>
