<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1572;CS1573;CS1591</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\common\Inno.Adapter\Inno.Adapter.csproj" />
    <ProjectReference Include="..\..\rendering\Inno.Adapter.Rendering.Authoring\Inno.Adapter.Rendering.Authoring.csproj" />
    <ProjectReference Include="..\..\..\services\platform\Inno.Platform\Inno.Platform.csproj" />
    <ProjectReference Include="..\..\..\services\rendering\Inno.Rendering\Inno.Rendering.csproj" />
  </ItemGroup>
</Project>
