using Inno.Rendering.Assets;
using Inno.Scripting.Api;

[assembly: ScriptingApiNamespace("InnoEngine.Rendering", "Inno.Rendering.Assets", ScriptingApiScope.Runtime)]

[assembly: ScriptingApiExport(typeof(RenderShaderArtifact), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderShaderPassArtifact), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderShaderStageArtifact), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderShaderVariant), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderPropertyBindingOwner), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderCullMode), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderCompareFunction), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderRenderState), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderContractId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderTechniqueId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderPassRoleId), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderMetadataEntry), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderPropertyDefinition), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderKeywordDefinition), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderPassDefinition), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderTechniquePass), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderTechniqueDefinition), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderDefinition), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(TextureColorSpace), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTextureArtifactSlot), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderTextureArtifactReference), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(IRenderTextureArtifactSource), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(TextureAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(GeometryAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderSourceLocation), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(ShaderDiagnostic), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialValueKind), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialValue), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialPropertyEntry), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialMetadataEntry), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialAsset), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialPropertyBlock), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialPassResolution), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(MaterialPassResolver), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(SerializedRenderExtensionState), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderFeatureConfiguration), ScriptingApiScope.Runtime)]
[assembly: ScriptingApiExport(typeof(RenderPipelineAsset), ScriptingApiScope.Runtime)]
