<Project>
  <PropertyGroup Condition="'$(InnoAssemblyDomain)' == ''">
    <InnoAssemblyDomain>InnoInternal</InnoAssemblyDomain>
  </PropertyGroup>
  <PropertyGroup Condition="'$(InnoAssemblyScope)' == ''">
    <InnoAssemblyScope>Runtime</InnoAssemblyScope>
  </PropertyGroup>
  <PropertyGroup Condition="'$(InnoScriptApi)' == ''">
    <InnoScriptApi>None</InnoScriptApi>
  </PropertyGroup>
  <PropertyGroup>
    <BGCSRuntimeProject Condition="'$(BGCSRuntimeProject)' == '' and Exists('$(MSBuildThisFileDirectory)..\..\BindGen-CS\src\BGCS.Runtime\BGCS.Runtime.csproj')">$(MSBuildThisFileDirectory)..\..\BindGen-CS\src\BGCS.Runtime\BGCS.Runtime.csproj</BGCSRuntimeProject>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MSBuildProjectName)' != 'Inno.Core.Serialization.Generators'">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1570;CS1572;CS1573;CS1591</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'Inno.Core.Serialization.Generators'">
    <ProjectReference
      Include="$(MSBuildThisFileDirectory)foundation/core/Inno.Core.Serialization.Generators/Inno.Core.Serialization.Generators.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
