<Project>
  <Import Project="../Directory.Build.props" />
  <PropertyGroup Condition="'$(InnoAssemblyDomain)' == ''">
    <InnoAssemblyDomain>InnoInternal</InnoAssemblyDomain>
  </PropertyGroup>
  <PropertyGroup Condition="'$(InnoAssemblyScope)' == ''">
    <InnoAssemblyScope>Runtime</InnoAssemblyScope>
  </PropertyGroup>
  <PropertyGroup Condition="'$(InnoScriptApi)' == ''">
    <InnoScriptApi>None</InnoScriptApi>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MSBuildProjectName)' != 'Inno.Core.Serialization.Generators'">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1570;CS1572;CS1573;CS1591</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'Inno.Core.Serialization.Generators' and '$(MSBuildProjectName)' != 'Inno.Runtime.Generators' and '$(MSBuildProjectName)' != 'Inno.Scripting.Compiler'">
    <ProjectReference
      Include="$(MSBuildThisFileDirectory)foundation/core/Inno.Core.Serialization.Generators/Inno.Core.Serialization.Generators.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
