<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);CS0108</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\native\Inno.Native.Sdl3\Inno.Native.Sdl3.csproj" />
    <ProjectReference Include="..\..\..\..\native\Inno.Native.ImGui\Inno.Native.ImGui.csproj" />
    <ProjectReference Include="$(BGCSRuntimeProject)" Condition="'$(BGCSRuntimeProject)' != ''" />
  </ItemGroup>
  <ItemGroup Condition="'$(BGCSRuntimeProject)' == ''">
    <PackageReference Include="BGCS.Runtime" Version="1.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Inno.Adapter.Presentation\Inno.Adapter.Presentation.csproj" />
    <ProjectReference Include="..\..\..\services\platform\Inno.Platform\Inno.Platform.csproj" />
    <ProjectReference Include="..\..\platform\Inno.Adapter.Platform.Sdl3\Inno.Adapter.Platform.Sdl3.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="BuiltIn\**\*.*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="BuiltIn\Icons\FA-Regular-400.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="BuiltIn\Icons\FA-Solid-900.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
